---
title: "core score prediction figs"
author: "Caroline Dravillas"
date: "2026-04-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(broom)
library(dplyr)
library(purrr)
library(forcats)
library(ggpubr)
library(MESS)
library(patchwork)
```

```{r}
load("../../data/randomforest-irae-corescore.rda")
load("../../data/randomforest-response-corescore.rda")
```


### Boxplots with upset plot style x-axis made in illustrator
```{r}
# function to plot AUCPR boxplots 
aucpr_box <- function(input){
  df <- input %>%
  select(Predictors, seed, AUCPR) %>%
  distinct()

# Reorder predictors by mean AUCPR (highest to lowest)
mean_order <- df %>%
  group_by(Predictors) %>%
  summarise(mean_aucpr = mean(AUCPR, na.rm = TRUE)) %>%
  arrange(mean_aucpr) %>%
  pull(Predictors)

pairwise_results <- compare_means(
  AUCPR ~ Predictors,
  data = df,
  method = "wilcox.test",   # non-parametric
  p.adjust.method = "BH"    # multiple comparison adjustment
)

# Keep only significant comparisons (adjusted p < 0.05)
significant_comparisons <- pairwise_results %>%
  filter(p.adj < 0.05) %>%
  select(group1, group2)

# Convert to list format for ggpubr
sig_list <- split(significant_comparisons[, c("group1","group2")],
                  seq(nrow(significant_comparisons))) %>%
  lapply(function(x) as.character(unlist(x)))

Means <- df %>%
  group_by(Predictors) %>%
  summarise(mean_aucpr = mean(AUCPR, na.rm = TRUE)) %>%
  arrange(mean_aucpr)

Model_Comparison_Plot <- df %>%
  ggplot(aes(
    x = fct_relevel(Predictors, mean_order),
    y = AUCPR,
    color = Predictors  # color controls box outline AND median line
  )) +
  geom_boxplot(outlier.colour = NA, fatten = 1) +  # median line inherits box color
  geom_jitter(width = 0.1, alpha = 0.6) +         # jitter points
  # ggpubr::stat_compare_means(
  #   comparisons = sig_list,
  #   label = "p.signif",
  #   label.y = seq(0.95, by = 0.1, length.out = length(sig_list))
  # ) +
  labs(y = "AUCPR", x = NULL, title = NULL) +
  scale_color_manual(values = c("cornflowerblue", "#EC8FA3FF", "#855C75FF", "cyan4","#FCBA65FF", "#8C9D57FF","darkgreen")) +
  scale_y_continuous(limits = c(0, max(df$AUCPR, na.rm = TRUE) + 0.1)) +
  theme(
    axis.title = element_text(size = 16),
    axis.text.x = element_text(angle = 45, hjust=1),
    legend.position = "none",
    axis.line = element_line(color = 'black', linewidth = 0.5),
    panel.background = element_rect(fill = 'white')
  ) +
 scale_y_continuous(
  limits = c(0.3, 1.0),
  breaks = seq(0.3, 1.0, 0.1)) +
  # annotate mean values below boxes
  annotate(
    geom = "text",
    x = seq_along(mean_order),
    y = 0.32,
    label = round(Means$mean_aucpr, 3),
    color = "black",
    size = 4
  )

  return(Model_Comparison_Plot)
}
```

```{r}
aucpr_box(pr_response_df)

ggsave("../../figures/corescore-AUCPR-boxplots-response.svg", height = 5, width = 5)
#ggsave("../../figures/corescore-AUCPR-boxplots-response.png", height = 5, width = 5)
```

```{r}
aucpr_box(pr_irae_df)
ggsave("../../figures/corescore-AUCPR-boxplots-irae.svg", height = 5, width = 5)
#ggsave("../../figures/corescore-AUCPR-boxplots-irae.png", height = 5, width = 5)
```

Figure E and F - ROC curves for mitox 
```{r}
pr_irae_df %>%
  select(AUCPR, Predictors, seed) %>%
  distinct() %>%
  group_by(Predictors) %>%
  summarise(avg.aucpr = mean(AUCPR)) %>%
  arrange(avg.aucpr)

pr_response_df %>%
  select(AUCPR, Predictors, seed) %>%
  distinct() %>%
  group_by(Predictors) %>%
  summarise(avg.aucpr = mean(AUCPR)) %>%
  arrange(avg.aucpr)

roc_irae_df %>%
  select(AUCROC, Predictors, seed) %>%
  distinct() %>%
  group_by(Predictors) %>%
  summarise(avg.auc = mean(AUCROC)) %>%
  arrange(avg.auc)

roc_response_df %>%
  select(AUCROC, Predictors, seed) %>%
  distinct() %>%
  group_by(Predictors) %>%
  summarise(avg.auc = mean(AUCROC)) %>%
  arrange(avg.auc)
```


```{r}
roc_response_df %>% 
  filter(Predictors %in% c("Microbiome", "Clinical")) %>%
  ggplot(aes(FalsePositive, TruePositive,
             colour = Predictors)) +
  geom_line(aes(group = interaction(seed, Predictors)),
            alpha = 0.1, linewidth = 0.4) +
  geom_smooth(aes(group = Predictors),
              se = FALSE, linewidth = 1.2) +
  scale_color_manual(values = c("cornflowerblue", "darkgreen")) +
  theme_minimal() +
  xlab("1 - Specificity") +
  ylab("Sensitivity") +
  # annotate(geom="text", x=0.8, y=0.26, label="AUC = 0.614",
  #          color="darkgreen", size=4) +
  # annotate(geom="text", x=0.8, y=0.16, label="AUC = 0.562",
  #          color="cornflowerblue", size=4) +
  theme(legend.position = "none")
```

```{r}
roc_irae_df %>% 
  filter(Predictors %in% c("Microbiome", "Clinical")) %>%
  ggplot(aes(FalsePositive, TruePositive,
             colour = Predictors)) +
  geom_line(aes(group = interaction(seed, Predictors)),
            alpha = 0.1, linewidth = 0.4) +
  geom_smooth(aes(group = Predictors),
              se = FALSE, linewidth = 1.2) +
  scale_color_manual(values = c("cornflowerblue", "darkgreen")) +
  theme_minimal() +
  xlab("1 - Specificity") +
  ylab("Sensitivity") +
  # annotate(geom="text", x=0.8, y=0.26, label="AUC = 0.773",
  #          color="darkgreen", size=4) +
  # annotate(geom="text", x=0.8, y=0.16, label="AUC = 0.489",
  #          color="cornflowerblue", size=4) +
  theme(legend.position = "none")

```

## Lets look at the variable importance for each of the models 
```{r}
plot_data_list <- lapply(imp_irae_list, function(val.r.vars) {

  val.r.vars %>%
    group_by(Factors) %>%
    summarise(meanGini = mean(MeanDecreaseGini, na.rm = TRUE)) %>%
    arrange(desc(meanGini)) %>%
    mutate(taxon = gsub("^[a-z]__", "", Factors)) 
    #left_join(res.recist, by = "Factors") %>%
    # mutate(
    #   `Effect Direction` = ifelse(lfc_ResponseResponder < 0, "Depleted", "Enriched"),
    #   taxon = gsub("_", " ", taxon)
    # )
})

plot_list <- lapply(plot_data_list, function(plot.in) {

  ggplot(plot.in,
         aes(x = reorder(taxon, meanGini),
             y = meanGini)) +
    #scale_fill_manual(values = c("#91BFDB", "#FC8D59")) +
    geom_col() +
    coord_flip() +
    labs(x = "", y = "Variable Importance") +
    theme_minimal()
})

plot_list_titled <- lapply(names(plot_list), function(nm) {

  plot_list[[nm]] +
    ggtitle(nm)
})
wrap_plots(plot_list_titled, ncol = 3)
```
```{r}
plot_data_list <- lapply(imp_response_list, function(val.r.vars) {

  val.r.vars %>%
    group_by(Factors) %>%
    summarise(meanGini = mean(MeanDecreaseGini, na.rm = TRUE)) %>%
    arrange(desc(meanGini)) %>%
    mutate(taxon = gsub("^[a-z]__", "", Factors)) 
    #left_join(res.recist, by = "Factors") %>%
    # mutate(
    #   `Effect Direction` = ifelse(lfc_ResponseResponder < 0, "Depleted", "Enriched"),
    #   taxon = gsub("_", " ", taxon)
    # )
})

plot_list <- lapply(plot_data_list, function(plot.in) {

  ggplot(plot.in,
         aes(x = reorder(taxon, meanGini),
             y = meanGini)) +
    #scale_fill_manual(values = c("#91BFDB", "#FC8D59")) +
    geom_col() +
    coord_flip() +
    labs(x = "", y = "Variable Importance") +
    theme_minimal()
})

plot_list_titled <- lapply(names(plot_list), function(nm) {

  plot_list[[nm]] +
    ggtitle(nm)
})
wrap_plots(plot_list_titled, ncol = 3)
```
