---
title: "deseq"
author: "Caroline Wheeler"
date: "2023-10-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(DESeq2)
library(tidyverse)
```

load data
```{r}
load("../../../data/old-processing-objects/taxonomy.rds")

load("../../data/taxonomy-long.rds")
load("../../data/clinical.rds")
load("../../data/microbiome_metadata.rds")
```

create inputs 
```{r}
baseline <- mic.meta %>%
  group_by(`Patient Id`) %>%
  arrange(Days) %>%
  slice_head(n = 1)

clin <- left_join(baseline, demographics, by = "Patient Id") %>%
  dplyr::filter(sample %in% tax.l$sample)

irae <- clin %>% 
  dplyr::select(sample, irAE) %>%
  dplyr::filter(sample %in% tax.l$sample)

taxa_irae <- tax.l %>%
  dplyr::filter(sample %in% irae$sample)

# response as ifelse(Category == "PD", "NR", "R")) for deseq
recist <- clin %>%
  dplyr::mutate(Response = ifelse(Category == "PD", "NR", "R")) %>%
  dplyr::select(sample, Response) %>%
  dplyr::filter(sample %in% tax.l$sample,
                !is.na(Response))

taxa_res <- tax.l %>%
  dplyr::filter(sample %in% recist$sample)

sub <- clin %>%
  dplyr::filter(Category != "PD",
                !is.na(Category),
                sample %in% tax.l$sample) %>%
  dplyr::select(sample, irAE)

taxa_sub <- tax.l %>%
  dplyr::filter(sample %in% sub$sample)
```

```{r}
spec.ra <- tax.l %>% filter(grepl("s__", microbe))
ggplot(spec.ra, aes(-log10(RelAbun*2083.33333333))) + geom_histogram(binwidth = 0.5)
```


## define functions
```{r}
# functions to get count tables - ideally 3 parts would be in one function, too annoying to resolve right now
#
# @taxa df - long form df of taxa
# @lev string - name of the taxonomic level
write_desd <- function(taxa, lev){
  desd <- taxa %>%
    dplyr::select("sample", all_of(lev), "RelAbun") %>%
    mutate(count = round(RelAbun*2083.33333333))%>%
    dplyr::select(-"RelAbun")
  
  return(desd)
}

write_desd_part2 <- function(desd){
  desd <- desd  %>%
    dplyr::select(-"count") %>%
    distinct() %>%
    spread(sample, n, fill = 0) %>%
    remove_rownames
  
  return(desd)
}

# write_desd_part3 <- function(desd){
#   desd <- desd %>%
#     mutate(Total = reduce(., `+`)) %>%
#     dplyr::filter(Total != 0) %>%
#     dplyr::select(-Total)
#   
#   return(desd)
# }

# function to run deseq2
#
# @desd
# @meta
# @lev
run_deseq <- function(desd, meta, lev){
  ord <- rownames(meta)
  desd <- desd[, ord]
  dds <- DESeqDataSetFromMatrix(countData = desd,
                                colData = meta,
                                # change design = according to which analysis 
                                design = ~ Response)

  dds <- DESeq(dds)
  res <- results(dds)
  
  pd <- res$log2FoldChange
  
  resPlot <- data.frame(res) %>% mutate(threshold = padj < 0.05)
  
  resPlot$level <- lev
  return(resPlot)
}
```

## irAE

# get irAE count tables
```{r}
phyl <- write_desd(taxa_irae, "phylum") %>%
  add_count(sample, phylum, wt=count) 
phyl <- write_desd_part2(phyl) %>% 
  column_to_rownames(var="phylum")
#phyl <- write_desd_part3(phyl)

class <- write_desd(taxa_irae, "class") %>%
  add_count(sample, class, wt=count) 
class <- write_desd_part2(class) %>% 
  column_to_rownames(var="class")
#class <- write_desd_part3(class)

ord <- write_desd(taxa_irae, "order") %>%
  add_count(sample, order, wt=count) 
ord <- write_desd_part2(ord) %>%
  column_to_rownames(var="order")
#ord <- write_desd_part3(ord)

fam <- write_desd(taxa_irae, "family") %>%
  add_count(sample, family, wt=count) 
fam <- write_desd_part2(fam) %>%
  column_to_rownames(var="family")
#fam <- write_desd_part3(fam)

gen <- write_desd(taxa_irae, "genus") %>%
  add_count(sample, genus, wt=count) 
gen <- write_desd_part2(gen) %>%
  column_to_rownames(var="genus")
#gen <- write_desd_part3(gen)

spec <- write_desd(taxa_irae, "species") %>%
  add_count(sample, species, wt=count) 
spec <- write_desd_part2(spec) %>%
  column_to_rownames(var="species")
#spec <- write_desd_part3(spec)
```

make sure cols and rows match and make samples rownames
```{r}
irae <- irae %>% arrange(factor(sample, levels = colnames(phyl))) %>%
  remove_rownames() %>%
  column_to_rownames(var = "sample")
```


# deseq2 for irAE
```{r}
phyl_rp <- run_deseq(phyl, irae, "phylum")
clas_rp <- run_deseq(class, irae, "class")
ord_rp <- run_deseq(ord, irae, "order")
fam_rp <- run_deseq(fam, irae, "family")
gen_rp <- run_deseq(gen+1, irae, "genus")

# add constant value to all cells in species matrix
# previously getting error
# Every gene contains at least one zero, cannot compute log geometric means
spec_rp <- run_deseq(spec+1, irae, "species")
```

```{r}
resPlot_irae <- rbind(phyl_rp, clas_rp, ord_rp, fam_rp, gen_rp, spec_rp)
save(resPlot_irae, file = "../../data/deseq_irae_baseline.rds")
```

## RECIST 

# get recist count tables
```{r}
phyl <- write_desd(taxa_res, "phylum") %>%
  add_count(sample, phylum, wt=count) 
phyl <- write_desd_part2(phyl) %>% 
  column_to_rownames(var="phylum")

class <- write_desd(taxa_res, "class") %>%
  add_count(sample, class, wt=count) 
class <- write_desd_part2(class) %>% 
  column_to_rownames(var="class")

ord <- write_desd(taxa_res, "order") %>%
  add_count(sample, order, wt=count) 
ord <- write_desd_part2(ord) %>%
  column_to_rownames(var="order")

fam <- write_desd(taxa_res, "family") %>%
  add_count(sample, family, wt=count) 
fam <- write_desd_part2(fam) %>%
  column_to_rownames(var="family")

gen <- write_desd(taxa_res, "genus") %>%
  add_count(sample, genus, wt=count) 
gen <- write_desd_part2(gen) %>%
  column_to_rownames(var="genus")

spec <- write_desd(taxa_res, "species") %>%
  add_count(sample, species, wt=count) 
spec <- write_desd_part2(spec) %>%
  column_to_rownames(var="species")
```

make sure cols and rows match and make samples rownames
```{r}
recist <- recist %>% arrange(factor(sample, levels = colnames(fam))) %>%
  remove_rownames() %>%
  column_to_rownames(var = "sample")
```

# deseq2 for recist
```{r}
phyl_rp <- run_deseq(phyl, recist, "phylum")
clas_rp <- run_deseq(class, recist, "class")
ord_rp <- run_deseq(ord, recist, "order")
fam_rp <- run_deseq(fam, recist, "family")
gen_rp <- run_deseq(gen+1, recist, "genus")

# add constant value to all cells in species matrix
# previously getting error
# Every gene contains at least one zero, cannot compute log geometric means
spec_rp <- run_deseq(spec + 1, recist, "species")
```

```{r}
resPlot_recist <- rbind(phyl_rp, clas_rp, ord_rp, fam_rp, gen_rp, spec_rp)

save(resPlot_recist, file = "../../data/deseq_recist_baseline.rds")
```


## SUBSET

# get subset count tables 
```{r}
phyl <- write_desd(taxa_sub, "phylum") %>%
  add_count(sample, phylum, wt=count) 
phyl <- write_desd_part2(phyl) %>% 
  column_to_rownames(var="phylum")

class <- write_desd(taxa_sub, "class") %>%
  add_count(sample, class, wt=count) 
class <- write_desd_part2(class) %>% 
  column_to_rownames(var="class")

ord <- write_desd(taxa_sub, "order") %>%
  add_count(sample, order, wt=count) 
ord <- write_desd_part2(ord) %>%
  column_to_rownames(var="order")

fam <- write_desd(taxa_sub, "family") %>%
  add_count(sample, family, wt=count) 
fam <- write_desd_part2(fam) %>%
  column_to_rownames(var="family")

gen <- write_desd(taxa_sub, "genus") %>%
  add_count(sample, genus, wt=count) 
gen <- write_desd_part2(gen) %>%
  column_to_rownames(var="genus")

spec <- write_desd(taxa_sub, "species") %>%
  add_count(sample, species, wt=count) 
spec <- write_desd_part2(spec) %>%
  column_to_rownames(var="species")
```

make sure cols and rows match and make samples rownames
```{r}
sub <- sub %>% arrange(factor(sample, levels = colnames(fam))) %>%
  remove_rownames() %>%
  column_to_rownames(var = "sample")
```

# deseq2 for recist
```{r}
phyl_rp <- run_deseq(phyl, sub, "phylum")
clas_rp <- run_deseq(class, sub, "class")
ord_rp <- run_deseq(ord, sub, "order")
fam_rp <- run_deseq(fam, sub, "family")
gen_rp <- run_deseq(gen+1, sub, "genus")

# add constant value to all cells in species matrix
# previously getting error
# Every gene contains at least one zero, cannot compute log geometric means
spec_rp <- run_deseq(spec + 1, sub, "species")
```

```{r}
resPlot_sub <- rbind(phyl_rp, clas_rp, ord_rp, fam_rp, gen_rp, spec_rp)

save(resPlot_sub, file = "../../data/deseq_subset_results_baseline.rds")
```

```{r}
load("../../data/deseq_recist.rds")
load("../../data/_deseq_subset_results.rds")
load("../../data/deseq_irae.rds")
```

