---
title: "Figure 4 - Longitudinal analysis for response"
author: "C. Dravillas"
date: "2025-04-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(ggrepel)
library(tidyverse)
library(ggfortify)
library(VennDiagram)
library(ggVennDiagram)
library(patchwork)
```

# Load data 

```{r}
load("../../data/ZIGMM-model-output.rds")
load("../../data/phylum-labels.rds")
load("../../data/clinical.rds")
load("../../data/microbiome_metadata.rds")
load("../../data/counts-long.rds")
load("../../data/ANCOM-BC2_response_baseline.RData")
```

# Prep 

```{r}
colors <- c("darkgreen","darkgoldenrod2","cyan4","cornflowerblue", "salmon2", "deeppink4") 
gmm.out <- gmm.out %>%
  left_join(phyl_labels) %>%
  mutate(label = ifelse(padj < 0.05, microbe, NA),
         Phylum = ifelse(padj < 0.05, Phylum, NA))
```

# Plot 

Figure 4A - Volcano Linear Term
```{r}
gmm.out %>%
  filter(padj < 1,
         term == "ResponseResponder:Days") %>%
  ggplot(aes(x=estimate, y=-log10(padj), label= label)) + 
  geom_point(aes(x=estimate, y=-log10(padj), color = Phylum)) +
  geom_text_repel(size = 2) + 
  scale_color_manual(values = colors, na.value = "honeydew3") +
  theme_bw(base_size = 9) +
  xlab("Estimate") +
  ylab("log10(p-value)") +
  guides(color = guide_legend(na.translate = FALSE))

ggsave("../../figures/Fig4A-ZIGMM-nonquad-volcano.png", height = 4, width = 7, dpi = 300)
```

```{r}
gmm.out %>%
  filter(padj < 1,
         term == "ResponseResponder:I(Days^2)") %>%
  ggplot(aes(x=estimate, y=-log10(padj), label= label)) + 
  geom_point(aes(x=estimate, y=-log10(padj), color = Phylum)) +
  geom_text_repel(size = 2) + 
  scale_color_manual(values = colors, na.value = "honeydew3") +
  theme_bw(base_size = 9) +
  xlab("Estimate") +
  ylab("log10(p-value)") +
  guides(color = guide_legend(na.translate = FALSE))

ggsave("../../figures/Fig4B-ZIGMM-quad-volcano.png", height = 4, width = 7, dpi = 300)
```

<!-- Volcano plots are looking pretty sparse. Quadratic terms seem almost not worth  -->
<!-- showing, the estimate is so small. lets try a lollipop plot to highlight P. plebeius  -->

<!-- ```{r} -->
<!-- gmm.out %>% -->
<!--   filter(padj < 0.05, -->
<!--          term == "ResponseResponder:Days") %>% -->
<!--   arrange(estimate) %>% -->
<!--   mutate(microbe = factor(microbe, levels = unique(microbe))) %>% -->
<!--   ggplot(aes(x = estimate, y = microbe)) + -->
<!--   geom_segment(aes(x = 0, xend = estimate, y = microbe, yend = microbe), color = "grey") + -->
<!--   geom_point(size = 3, color = "steelblue") + -->
<!--   facet_wrap(~ term, scales = "free_y") + -->
<!--   theme_minimal() + -->
<!--   labs(x = "Estimate (LMM)", y = "Microbe")  -->

<!-- ggsave("../../figures/exploratory-ZIGMM-nonquad-lolipop.png", height = 4, width = 7, dpi = 300) -->
<!-- ``` -->

Figure 4C - line plot

```{r}
vis.in.c <- counts.l %>%
  mutate(microbe = str_extract(Taxonomy, "[^|]+$")) %>%
  dplyr::select(-Taxonomy) %>%
  pivot_wider(names_from = microbe, values_from = est.reads, values_fill = 0) %>%
  pivot_longer(!sample, names_to = "microbe", values_to = "est.reads") %>%
  left_join(mic.meta) %>%
  right_join(demographics) %>%
  # create binary outcome var
  mutate(response.bin = ifelse(Response == "Responder", 1, 0),
  # make days numeric
         Days = as.integer(Days),
  # create quadratic days
         Days2 = Days^2) %>%
  rename(Patient_Id = `Patient Id`)
```

```{r}
vis.in.c %>% 
  filter(microbe == "s__Phocaeicola_plebeius") %>%
  ggplot(aes(x = Days, y = est.reads, group = Patient_Id, color = Response)) +
  scale_color_manual(values = c("#E69F00", "#3B9AB2")) +
  geom_line(alpha = 0.5) +
  geom_smooth(
    aes(group = Response),
    method = "loess",
    se = FALSE,
    linewidth = 1.2
  ) +
  theme_minimal()

ggsave("../../figures/Fig4C-lineplot.png", height = 4, width = 5, dpi = 300)
```

# Figure 4D - Venn Diagram(s)

```{r}
gmm.out <- gmm.out %>%
  mutate(taxon = substr(microbe, 4, nchar(microbe)))

ancom.r <- (res.recist %>%
  filter(q_ResponseResponder < 0.05,
         lfc_ResponseResponder > 0))$taxon
ancom.nr <- (res.recist %>%
  filter(q_ResponseResponder < 0.05,
         lfc_ResponseResponder < 0))$taxon

r.padj <- (gmm.out %>%
  filter(term == "ResponseResponder",
         padj < 0.05,
         estimate > 0))$taxon
nr.padj <- (gmm.out %>%
  filter(term == "ResponseResponder",
         padj < 0.05,
         estimate < 0))$taxon

r.pval <- (gmm.out %>%
  filter(term == "ResponseResponder",
         p.value < 0.05,
         estimate > 0))$taxon
nr.pval <- (gmm.out %>%
  filter(term == "ResponseResponder",
         p.value < 0.05,
         estimate < 0))$taxon

r.pval.1 <- (gmm.out %>%
  filter(term == "ResponseResponder",
         p.value < 0.1,
         estimate > 0))$taxon
nr.pval.1 <- (gmm.out %>%
  filter(term == "ResponseResponder",
         p.value < 0.1,
         estimate < 0))$taxon
```
"#E69F00", "#3B9AB2"
```{r}
p1 <- ggVennDiagram(list(ANCOM = ancom.nr, GMM.padj = nr.padj), label = "count", label_alpha = 0) +
  scale_fill_gradient(low = "white", high = "#E69F00")  +
  theme(legend.position = "none") +
  xlim(-10, 10) 
p2 <- ggVennDiagram(list(ANCOM = ancom.r, GMM.padj = r.padj), label = "count", label_alpha = 0) +
  scale_fill_gradient(low = "white", high = "#3B9AB2") +
  theme(legend.position = "none") +
  xlim(-10, 10) 

p3 <- ggVennDiagram(list(ANCOM = ancom.nr, GMM.pval.05 = nr.pval), label = "count", label_alpha = 0) +
  scale_fill_gradient(low = "white", high = "#E69F00")  +
  theme(legend.position = "none") +
  xlim(-10, 10) 
p4 <- ggVennDiagram(list(ANCOM = ancom.r, GMM.pval.05 = r.pval), label = "count", label_alpha = 0) +
  scale_fill_gradient(low = "white", high = "#3B9AB2") +
  theme(legend.position = "none") +
  xlim(-10, 10) 

p5 <- ggVennDiagram(list(ANCOM = ancom.nr, GMM.pval.1 = nr.pval.1), label = "count", label_alpha = 0) +
  scale_fill_gradient(low = "white", high = "#E69F00")  +
  theme(legend.position = "none") +
  xlim(-10, 10) 
p6 <- ggVennDiagram(list(ANCOM = ancom.r, GMM.pval.1 = r.pval.1), label = "count", label_alpha = 0) +
  scale_fill_gradient(low = "white", high = "#3B9AB2") +
  theme(legend.position = "none") +
  xlim(-10, 10) 
```


```{r}
(p1 | p2 ) /
(p3 | p4 ) /
(p5 | p6)
```
```{r}
final_plot <- (p1 | p2) /
              (p3 | p4) /
              (p5 | p6)

ggsave("../../figures/Fig4D-venn.svg", final_plot,
       width = 4, height = 7, dpi = 300)
```


```{r}
nr.padj.v
r.padj.v

nr.pval.v
r.pval.v

nr.pval.1.v
r.pval.1.v
```



