---
title: "Figure 5"
author: "C. Dravillas"
date: "2025-05-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(ggrepel)
library(tidyverse)
library(ggfortify)
library(VennDiagram)
library(ggVennDiagram)
library(patchwork)
```

# Load data 

```{r}
load("../../data/ZIGMM-model-output-irAE.rds")
load("../../data/phylum-labels.rds")
load("../../data/clinical.rds")
load("../../data/microbiome_metadata.rds")
load("../../data/counts-long.rds")
load("../../data/ANCOM-BC2_irae_baseline.RData")
load("../../data/irae.rds")
load("../../data/core-score-min3.rds")
```

# Prep 

```{r}
colors <- c("darkgreen","darkgoldenrod2","cyan4","cornflowerblue", "salmon2", "deeppink4") 
gmm.out <- gmm.out.mic %>%
  left_join(phyl_labels) %>%
  mutate(label = ifelse(padj < 0.05, microbe, NA),
         Phylum = ifelse(padj < 0.05, Phylum, NA))
```

# Plot 

Figure 4A - Volcano Linear Term, didn't include the quadratic term in the model
```{r}
gmm.out %>%
  filter(padj < 1) %>%
  ggplot(aes(x=estimate, y=-log10(padj), label= label)) + 
  geom_point(aes(x=estimate, y=-log10(padj), color = Phylum)) +
  geom_text_repel(size = 2) + 
  scale_color_manual(values = colors, na.value = "honeydew3") +
  theme_bw(base_size = 9) +
  xlab("Estimate") +
  ylab("log10(p-value)") +
  guides(color = guide_legend(na.translate = FALSE))

ggsave("../../figures/Fig5A-ZIGMM-nonquad-volcano-irae.svg", height = 4, width = 7, dpi = 300)
```

Figure 5B - line plot ?

```{r}
vis.in.c <- counts.l %>%
  mutate(microbe = str_extract(Taxonomy, "[^|]+$")) %>%
  dplyr::select(-Taxonomy) %>%
  pivot_wider(names_from = microbe, values_from = est.reads, values_fill = 0) %>%
  pivot_longer(!sample, names_to = "microbe", values_to = "est.reads") %>%
  left_join(mic.meta) %>%
  right_join(demographics) %>%
  # create binary outcome var
  mutate(response.bin = ifelse(Response == "Responder", 1, 0),
  # make days numeric
         Days = as.integer(Days),
  # create quadratic days
         Days2 = Days^2) %>%
  rename(Patient_Id = `Patient Id`) |>
  filter(microbe == "s__Phocaeicola_dorei") 
```

```{r}
irae.time <- irae |>
  mutate(irae.days = as.integer(Days)) |>
  rename(Patient_Id = `Patient Id`) |>
  select(-Days) |>
  right_join(vis.in.c) 

# irae.time %>% 
#   filter(microbe == "s__Phocaeicola_dorei") %>%
#   ggplot(aes(x = Days, y = est.reads, group = Patient_Id, color = irAE)) +
#   scale_color_manual(values = c("#E69F00", "#3B9AB2")) +
#   geom_line(alpha = 0.5) +
#   geom_smooth(
#     aes(group = irAE),
#     method = "loess",
#     se = FALSE,
#     linewidth = 1.2
#   ) +
#   theme_minimal()

points_df <- tibble(Patient_Id = character(),
                    irAE = character(),
                    Days_event = numeric(),
                    est.reads = numeric())

patients <- unique(irae.time$Patient_Id)

for (pid in patients) {
  # get patient's irAE status
  patient_irAE <- unique(irae.time$irAE[irae.time$Patient_Id == pid])
  
  # skip if irAE is "No"
  if (patient_irAE == "No") next
  
  # check if patient has this microbe present at any timepoint
  patient_data <- irae.time %>%
    filter(Patient_Id == pid) %>%
    filter(!is.na(Days) & !is.na(est.reads)) %>%
    distinct(Days, est.reads)
  
  # skip if the patient never has the microbe
  if (nrow(patient_data) == 0 || all(patient_data$est.reads == 0)) next
  
  # get this patient's irAE event days
  patient_events <- unique(irae.time$irae.days[irae.time$Patient_Id == pid])
  
  for (d in patient_events) {
    if (nrow(patient_data) >= 2) {
      y <- approx(x = patient_data$Days,
                  y = patient_data$est.reads,
                  xout = d,
                  rule = 2)$y
    } else {
      y <- patient_data$est.reads[1]
    }
    
    points_df <- bind_rows(points_df,
                           tibble(Patient_Id = pid,
                                  irAE = "Yes",
                                  Days_event = d,
                                  est.reads = y))
  }
}
ggplot(irae.time, aes(x = Days, y = est.reads, group = Patient_Id, color = irAE)) +
  geom_line(alpha = 0.5) +
  geom_smooth(aes(group = irAE), method = "loess", se = FALSE, linewidth = 1.2) +
  geom_point(
    data = points_df,
    aes(x = Days_event, y = est.reads, color = irAE),
    shape = 4, color = "black", size = 3, stroke = 1
  ) +
  scale_color_manual(values = c("#E69F00", "#3B9AB2")) +
  theme_minimal()


ggsave("../../figures/Fig5C-lineplot.svg", height = 4.5, width = 5, dpi = 300)
```

# Figure 5C - Venn Diagram(s)

```{r}
gmm.out <- gmm.out.mic %>%
  mutate(taxon = substr(microbe, 4, nchar(microbe)))

ancom.irae <- (res.irae %>%
  filter(q_irAEYes < 0.05,
         lfc_irAEYes > 0))$taxon
ancom <- (res.irae %>%
  filter(q_irAEYes < 0.05,
         lfc_irAEYes < 0))$taxon

padj.irae <- (gmm.out %>%
  filter(padj < 0.05,
         estimate > 0))$taxon
padj <- (gmm.out %>%
  filter(padj < 0.05,
         estimate < 0))$taxon

pval.irae <- (gmm.out %>%
  filter(p.value < 0.05,
         estimate > 0))$taxon
pval <- (gmm.out %>%
  filter(p.value < 0.05,
         estimate < 0))$taxon

pval.1.irae <- (gmm.out %>%
  filter(p.value < 0.1,
         estimate > 0))$taxon
pval.1 <- (gmm.out %>%
  filter(p.value < 0.1,
         estimate < 0))$taxon
```


```{r}
p1 <- ggVennDiagram(list(ANCOM = ancom.irae, GMM.padj = padj.irae), label = "count", label_alpha = 0) +
  scale_fill_gradient(low = "white", high = "darkgoldenrod2")  +
  theme(legend.position = "none") +
  xlim(-10, 10) 
p2 <- ggVennDiagram(list(ANCOM = ancom, GMM.padj = padj), label = "count", label_alpha = 0) +
  scale_fill_gradient(low = "white", high = "cyan4") +
  theme(legend.position = "none") +
  xlim(-10, 10) 

p3 <- ggVennDiagram(list(ANCOM = ancom.irae, GMM.pval.05 = pval.irae), label = "count", label_alpha = 0) +
  scale_fill_gradient(low = "white", high = "darkgoldenrod2")  +
  theme(legend.position = "none") +
  xlim(-10, 10) 
p4 <- ggVennDiagram(list(ANCOM = ancom, GMM.pval.05 = pval), label = "count", label_alpha = 0) +
  scale_fill_gradient(low = "white", high = "cyan4") +
  theme(legend.position = "none") +
  xlim(-10, 10) 

p5 <- ggVennDiagram(list(ANCOM = ancom.irae, GMM.pval.1 = pval.1.irae), label = "count", label_alpha = 0) +
  scale_fill_gradient(low = "white", high = "darkgoldenrod2")  +
  theme(legend.position = "none") +
  xlim(-10, 10) 
p6 <- ggVennDiagram(list(ANCOM = ancom, GMM.pval.1 = pval.1), label = "count", label_alpha = 0) +
  scale_fill_gradient(low = "white", high = "cyan4") +
  theme(legend.position = "none") +
  xlim(-10, 10) 
```


```{r}
(p2 | p1 ) /
(p4 | p3 ) /
(p6 | p5)
```
```{r}
final_plot <- (p1 | p2) /
              (p3 | p4) /
              (p5 | p6)

ggsave("../../figures/Fig5C-venn.svg", final_plot,
       width = 4, height = 7, dpi = 300)
```

# Figure 5D - SCHEMA

# Figure 5E - Boxplots core score

aes(x = irae.status, y = core.score)

```{r}
core_df |> 
  ggplot(aes(x = irAE, y = core.fraction, fill = irAE)) +
  geom_boxplot(alpha = 0.7, outlier.shape = NA) +
  geom_jitter(width = 0.2, alpha = 0.4) +
  theme_bw() +
  labs(x = "irAE", y = "Core score") +
  scale_fill_manual(values = c("#E69F00", "#3B9AB2")) +
  #stat_compare_means(method = "wilcox.test") +
  theme(legend.position = "none")

ggsave("../../figures/Fig5E-boxplot.svg", height = 4.5, width = 5, dpi = 300)
```



