---
title: "Figure 6 - predictive modeling"
author: "C. Dravillas"
date: "2025-09-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(broom)
library(dplyr)
library(purrr)
library(forcats)
library(ggpubr)
```

# Load data 
```{r}
load("../../data/clinical.rds")
load("../../data/microbiome_metadata.rds")
# load("../../../exploratory/data/randomforest-irae.rds")
# load("../../../exploratory/data/randomforest-response.rds")
# load("../../../exploratory/data/randomforest-irae-boruta.rds")
# load("../../../exploratory/data/randomforest-response-boruta.rds")
load("../../../exploratory/data/randomforest-irae-bor.rds")
load("../../../exploratory/data/randomforest-response-bor.rds")
# load("../../../exploratory/data/randomforest-irae-RFE.rds")
# load("../../../exploratory/data/randomforest-response-RFE.rds")
# load("../../../exploratory/data/randomforest-irae-rfe.rds")
# load("../../../exploratory/data/randomforest-response-rfe.rds")
```

# Prepare data
```{r}
baseline <- mic.meta %>%
  group_by(`Patient Id`) %>%
  arrange(Days) %>%
  slice_head(n = 1) %>%
  ungroup() %>%
  filter(abs(Days) <= 10)

# drops one person who does not have a baseline sample
demo.filt <- demographics %>%
  filter(`Patient Id` %in% baseline$`Patient Id`) %>%
  mutate(Response = factor(Response, levels = c("Non-Responder", "Responder")), 
         irAE = factor(irAE,     levels = c("No", "Yes"))) %>%
    rename(
    BMI = `BMI.(kg/m2)`,
    Absolute_lymphocytes = `Absolute.lymphocytes.(K/µL)`,
    LDH = `LDH.(U/L)`,
    Treatment.cat = Treatment, 
    Treatment = Treatment.bin
  )
```

# Figure 6A - Forest plots of clinical variables 

## Check for complete separation 
```{r}
cont_vars <- c("Age", "BMI", "Absolute_lymphocytes", "LDH")

cat_vars  <- c("Sex", "Treatment", "Stage", "PPI", "Antibiotics",
               "Corticosteroids", "Smoker")

check_separation <- function(data, outcome, cat_vars) {
  sapply(cat_vars, function(var) {
    tbl <- table(data[[var]], data[[outcome]])
    any(rowSums(tbl == 0) > 0)  # TRUE if any level has only 0s for an outcome
  })
}

check_separation(demo.filt, "irAE", cat_vars)
check_separation(demo.filt, "Response", cat_vars)
```

## Prepare
```{r}
# remove smoker var
cat_vars  <- c("Sex", "Treatment", "Stage", "PPI", "Antibiotics", "Corticosteroids")

# demo.filt <- demo.filt %>%
#   mutate(across(all_of(cat_vars), as.factor))

run_univariate <- function(outcome, data, cont_vars, cat_vars) {
  
  # continuous predictors
  cont_results <- map_dfr(cont_vars, ~ {
    formula <- as.formula(paste(outcome, "~", .x))
    tidy(glm(formula, data = data, family = binomial), conf.int = TRUE, exponentiate = TRUE) %>%
      filter(term != "(Intercept)") %>%
      mutate(Variable = .x)
  })
  
  # categorical predictors (each level vs reference)
  cat_results <- map_dfr(cat_vars, ~ {
    formula <- as.formula(paste(outcome, "~", .x))
    tidy(glm(formula, data = data, family = binomial), conf.int = TRUE, exponentiate = TRUE) %>%
      filter(term != "(Intercept)") %>%
      mutate(Variable = .x)
  })
  
  bind_rows(cont_results, cat_results) %>%
    rename(OR = estimate, CI_low = conf.low, CI_high = conf.high)
}

results_response <- run_univariate("Response", demo.filt, cont_vars, cat_vars)
results_irae     <- run_univariate("irAE",     demo.filt, cont_vars, cat_vars)
```

## Create Labels
```{r}
results_response <- results_response %>%
  mutate(Label = case_when(
    term == "Age" ~ "Age (years)",
    term == "BMI" ~ "BMI (kg/m2)",
    term == "Absolute_lymphocytes" ~ "Absolute lymphocytes",
    term == "LDH" ~ "LDH",
    term == "SexMale" ~ "Male vs Female",
    term == "TreatmentAnti-PD-1" ~ "Anti PD-1 vs Anti-CTLA-4",
    term == "StageStage IV" ~ "Stage IV vs III",
    term == "PPIYes" ~ "PPI (Yes vs No)",
    term == "AntibioticsYes" ~ "Antibiotics (Yes vs No)",
    term == "CorticosteroidsYes" ~ "Corticosteroids (Yes vs No)",
    TRUE ~ term
  )) %>%
  mutate(Significant = ifelse(CI_low > 1 | CI_high < 1, TRUE, FALSE))

results_irae <- results_irae %>%
  mutate(Label = case_when(
    term == "Age" ~ "Age (years)",
    term == "BMI" ~ "BMI (kg/m2)",
    term == "Absolute_lymphocytes" ~ "Absolute lymphocytes",
    term == "LDH" ~ "LDH",
    term == "SexMale" ~ "Male vs Female",
    term == "TreatmentAnti-PD-1" ~ "Anti PD-1 vs Anti-CTLA-4",
    term == "StageStage IV" ~ "Stage IV vs III",
    term == "PPIYes" ~ "PPI (Yes vs No)",
    term == "AntibioticsYes" ~ "Antibiotics (Yes vs No)",
    term == "CorticosteroidsYes" ~ "Corticosteroids (Yes vs No)",
    TRUE ~ term
  )) %>%
  mutate(Significant = ifelse(CI_low > 1 | CI_high < 1, TRUE, FALSE))
```


## Plot

### Univariate Clinical Predictors of Response
```{r}
ggplot(results_response, aes(x = OR, y = reorder(Label, OR))) +
  geom_point(size = 3) +
  geom_errorbarh(aes(xmin = CI_low, xmax = CI_high), height = 0.25) +
  geom_vline(xintercept = 1, linetype = "dashed", color = "deeppink4") +
  theme_minimal() +
  labs(
    title = "Response",
    x = "Odds Ratio (95% CI)",
    y = NULL,
  ) +
  theme(text = element_text(size = 14))

ggsave("../../figures/Fig6A-Forestplot-irae.svg", height = 2.5, width = 4)
```

### Univariate Clinical Predictors of irAE
```{r}
ggplot(results_irae, aes(x = OR, y = reorder(Label, OR))) +
  geom_point(size = 3) +
  geom_errorbarh(aes(xmin = CI_low, xmax = CI_high), height = 0.25) +
  geom_vline(xintercept = 1, linetype = "dashed", color = "deeppink4") +
  theme_minimal() +
  labs(
    title = "irAE",
    x = "Odds Ratio (95% CI)",
    y = NULL
  ) +
  theme(text = element_text(size = 14))

ggsave("../../figures/Fig6B-Forestplot-response.svg", height = 2.5, width = 4)
```

### upset plot style fig? or maybe just boxplots
```{r}
# function to plot AUCPR boxplots 
aucpr_box <- function(input){
  df <- input %>%
  select(Predictors, seed, AUCPR) %>%
  distinct()

# Reorder predictors by mean AUCPR (highest to lowest)
mean_order <- df %>%
  group_by(Predictors) %>%
  summarise(mean_aucpr = mean(AUCPR, na.rm = TRUE)) %>%
  arrange(mean_aucpr) %>%
  pull(Predictors)

pairwise_results <- compare_means(
  AUCPR ~ Predictors,
  data = df,
  method = "wilcox.test",   # non-parametric
  p.adjust.method = "BH"    # multiple comparison adjustment
)

# Keep only significant comparisons (adjusted p < 0.05)
significant_comparisons <- pairwise_results %>%
  filter(p.adj < 0.05) %>%
  select(group1, group2)

# Convert to list format for ggpubr
sig_list <- split(significant_comparisons[, c("group1","group2")],
                  seq(nrow(significant_comparisons))) %>%
  lapply(function(x) as.character(unlist(x)))

Means <- df %>%
  group_by(Predictors) %>%
  summarise(mean_aucpr = mean(AUCPR, na.rm = TRUE)) %>%
  arrange(mean_aucpr)

Model_Comparison_Plot <- df %>%
  ggplot(aes(
    x = fct_relevel(Predictors, mean_order),
    y = AUCPR,
    color = Predictors  # color controls box outline AND median line
  )) +
  geom_boxplot(outlier.colour = NA, fatten = 1) +  # median line inherits box color
  geom_jitter(width = 0.1, alpha = 0.6) +         # jitter points
  # ggpubr::stat_compare_means(
  #   comparisons = sig_list,
  #   label = "p.signif",
  #   label.y = seq(0.95, by = 0.1, length.out = length(sig_list))
  # ) +
  labs(y = "AUCPR", x = NULL, title = NULL) +
  scale_color_manual(values = c("firebrick4", "darkgoldenrod2", "cornflowerblue","salmon2","deeppink4", "cyan4","darkgreen")) +
  scale_y_continuous(limits = c(0, max(df$AUCPR, na.rm = TRUE) + 0.1)) +
  theme(
    axis.title = element_text(size = 16),
    axis.text.x = element_text(angle = 45, hjust=1),
    legend.position = "none",
    axis.line = element_line(color = 'black', linewidth = 0.5),
    panel.background = element_rect(fill = 'white')
  ) +
  scale_y_continuous(limits = c(0, 1.1), breaks = seq(0, 1, 0.1)) +
  # annotate mean values below boxes
  annotate(
    geom = "text",
    x = seq_along(mean_order),
    y = 0.03,
    label = round(Means$mean_aucpr, 3),
    color = "black",
    size = 4
  )

  return(Model_Comparison_Plot)
}
```

```{r}
aucpr_box(irae.rf %>% filter(Predictors != "Full Microbiome"))

ggsave("../../figures/Fig6D-AUCPR-boxplots-irae.svg", height = 5, width = 5)
```

```{r}
aucpr_box(response.rf  %>% filter(Predictors != "Full Microbiome"))

ggsave("../../figures/Fig6C-AUCPR-boxplots-response.svg", height = 5, width = 5)
```

Figure E and F - ROC curves

```{r}
response.rf %>% 
  filter(Predictors == "Microbiome" | Predictors=="Clinical") %>%
  group_by(Predictors) %>%
  mutate(max_AUCPR = max(AUCPR)) %>%
  filter(AUCPR == max_AUCPR) %>%
  select(-max_AUCPR) %>%
  ungroup() %>%
  ggplot(aes(FalsePositive, TruePositive, group = interaction(seed, Predictors), 
             colour = Predictors)) +
  scale_color_manual(values = c("cornflowerblue", "darkgreen")) +
  theme_minimal() +
  geom_smooth(se = FALSE) +
  xlab("Specifity") +
  ylab("Sensitivity") +
  annotate(geom="text", x=0.5, y=0.92, label="AUC = 0.993",
              color="darkgreen", size=4) +
  annotate(geom="text", x=0.55, y=0.73, label="AUC = 0.856",
              color="cornflowerblue", size=4) +
  theme(legend.position = "none")

ggsave("../../figures/Fig6E-ROC-response.svg", height = 2.5, width = 2.5)
```

```{r}
irae.rf %>% 
  filter(Predictors == "Microbiome" | Predictors=="Clinical") %>%
  group_by(Predictors) %>%
  mutate(max_AUCPR = max(AUCPR)) %>%
  filter(AUCPR == max_AUCPR) %>%
  select(-max_AUCPR) %>%
  ungroup() %>%
  ggplot(aes(FalsePositive, TruePositive, group = interaction(seed, Predictors), 
             colour = Predictors)) +
  scale_color_manual(values = c("cornflowerblue", "darkgreen")) +
  theme_minimal() +
  geom_smooth(se = FALSE) +
  xlab("Specifity") +
  ylab("Sensitivity") +
  annotate(geom="text", x=0.4, y=0.92, label="AUC = 1.0",
              color="darkgreen", size=4) +
  annotate(geom="text", x=0.75, y=0.45, label="AUC = 0.670",
              color="cornflowerblue", size=4) +
  theme(legend.position = "none")


ggsave("../../figures/Fig6F-ROC-irae.svg", height = 2.5, width = 2.5)
```


Figure G and H - ROC validation 

```{r}

```

Figure I and J - Variable Importance Plots

