---
title: "figure 2 - The association of gut microbes and T-cell senescence markers with treatment response"
author: "Caroline Wheeler"
date: "2023-10-24"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(ggrepel)
library(tidyverse)
library(ggfortify)
library(ggpubr)
```

# Load data 
```{r}
load("../../data/ra-long.rds")
load("../../data/clinical.rds")
load("../../data/microbiome_metadata.rds")
load("../../data/counts-wide.rds")
load("../../data/ANCOM-BC2_response_baseline.RData")
load("../../data/phylum-labels.rds")
load("../../data/taxonomy-key.rds")
load("../../data/ANCOM-BC2-fulltax-sigq_NR_irAE.rds")
load("../../data/ANCOM-BC2-fulltax-sigq_R_No_irAE.rds")
load("../../data/struct0_response.rds")
load("../../data/struct0_irae.rds")
load("../../data/alpha-diversity.rds")
load("../../data/respondersig-output.rds")
load("../../data/respondersig-output-baseline.rds")
# load("../../data/vsc.rds")
# vir.key <- read.csv("../../data/CRISPR_VSG-to-species.csv", sep = "\t")
```

# Figure Features 
```{r}
colors <- c("#6699CC", "#999933", "#CC6677","#44AA99","#DDCC77","#882255")
colors <- c("cyan4", "darkgoldenrod2", "darkgreen", "salmon2", "cornflowerblue", "deeppink4") 

# Response ID's
resp.id <- mic.meta %>%
  left_join(demographics) %>%
  select(sample, Days, Response)

# baseline samples 
base.samps <- mic.meta %>% 
  group_by(`Patient Id`) %>%
  arrange(Days) %>%
  slice_head(n = 1) %>%
  ungroup() %>%
  filter(abs(Days) <= 10)
```

Figure 2A - Stacked Bar (RA)
```{r}
phyl.ra <- ra.l %>%
  filter(grepl("p__", microbe))

top.phyl <- phyl.ra %>%
  group_by(microbe) %>%
  summarise(med.abun = median(RelAbun)) %>%
  arrange(desc(med.abun)) %>%
  filter(med.abun > 0)

phyl.ra <- phyl.ra %>%
  mutate(Phylum = ifelse(microbe %in% top.phyl$microbe, gsub("p__", "", microbe), 
                         "Other")) %>%
  left_join(resp.id)

# phyl.ra %>%
#   filter(RelAbun > 0) %>%
#   ggplot(aes(x = RelAbun)) +
#   facet_wrap(vars(microbe)) +
#   geom_histogram() 

# reorder samples by the total relative abundance of Firmicutes
phyl.ra <- phyl.ra %>%
  group_by(sample) %>%
  mutate(Firmicutes_Abundance = sum(RelAbun[Phylum == "Firmicutes"], na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(sample = fct_reorder(sample, Firmicutes_Abundance))

# order of microbes with 'other' last
phyl.ra <- phyl.ra %>%
  mutate(Phylum = factor(Phylum, levels = c(
    "Firmicutes", 
    setdiff(unique(Phylum), c("Firmicutes", "Other")), 
    "Other")))

# all samples 
# phyl.ra %>%
#   ggplot(aes(x = sample, y = RelAbun, fill = Phylum)) +
#   geom_bar(position="fill", stat = "identity") +
#   scale_fill_manual(values = colors) + 
#   labs(x = "", y = "") +
#   theme_minimal(base_size = 7) +
#   theme(axis.text.x = element_blank(),
#         axis.ticks.x = element_blank(),
#         axis.text.y = element_blank(),
#         panel.grid.major = element_blank(),
#         legend.position = "bottom",
#         legend.box = "horizontal",
#         legend.title = element_blank()) +
#   facet_grid(~Response, scales = "free_x", space = "free") +
#   guides(fill = guide_legend(ncol = 6, nrow = 1, byrow = TRUE))

# ggsave("../../figures/fig2a-stackedbar.png", height = 4, width = 6)

#baseline samples only
phyl.ra %>%
  filter(sample %in% base.samps$sample) %>%
  ggplot(aes(x = sample, y = RelAbun, fill = Phylum)) +
  geom_bar(position = "fill", stat = "identity") +
  scale_fill_manual(values = colors) + 
  labs(x = "", y = "") +
  theme_minimal(base_size = 9) +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.major = element_blank(),
    legend.position = "top",
    legend.box = "horizontal",
    legend.title = element_blank(),
    strip.placement = "outside", # Moves facet labels outside
    strip.background = element_blank(), # Optional: Removes the background of facet labels
    strip.text.x = element_text(size = 9) # Adjusts facet label text size
  ) +
  facet_grid(~Response, scales = "free_x", space = "free", switch = "x") +
  guides(fill = guide_legend(ncol = 6, nrow = 1, byrow = TRUE))

ggsave("../../figures/Fig2A-response-baseline-stackedbar.png", height = 3.5, width = 5, dpi = 500)
```

Figure 2B - Alpha Diversity 
# boxplots - look terrible 
```{r}
div  %>%
  filter(data.type == "RA",
         Signature != "Inverse.Simpson") %>%
  ggplot(aes(x=Response, y=log(Score))) +
  geom_boxplot(aes(fill = Response)) + 
  facet_wrap(~Signature, scales = "free") + 
  theme_bw(base_size = 7) +
  scale_fill_manual(values=c("deeppink4", "cornflowerblue")) +
  theme(legend.position = "none") +
  stat_compare_means(
    method = "t.test",
    size = 2.5,          # smaller font
    vjust = 13          # push lower vertically
  )

ggsave("../../figures/Fig2B-boxplots_diversity-response.png", width = 3, height = 3, dpi = 500)
```

Figure 2C - Volcano Plot R vs. NR
```{r}
phyl_labels <- phyl_labels %>%
  mutate(taxon = substr(microbe, 4, nchar(microbe)))

res.recist <- res.recist %>%
  left_join(phyl_labels) %>%
  mutate(Phylum = ifelse(q_ResponseResponder < 0.05 & abs(lfc_ResponseResponder) > 1, 
                         ifelse(Phylum %in% phyl.ra$Phylum, Phylum, "Other"), NA),
         taxon = gsub("_", " ", taxon),
        Phylum = factor(Phylum, levels = c(
    "Firmicutes", "Bacteroidota", "Actinobacteria", "Proteobacteria", "Other")),
    label = ifelse(taxon %in% sig.NR.irAE$taxon | taxon %in% sig.R.NoirAE$taxon, taxon, NA))

colors <- c("#6699CC", "#999933", "#CC6677","#44AA99","#882255")
colors <- c("cyan4", "darkgoldenrod2", "darkgreen", "salmon2", "deeppink4") 
```

```{r}
g <- res.recist %>%
  filter(q_ResponseResponder < 1) %>%
  ggplot(aes(x=lfc_ResponseResponder, y=-log10(q_ResponseResponder), label = label)) + 
  geom_point(aes(x=lfc_ResponseResponder, y=-log10(q_ResponseResponder), color = Phylum)) + 
  geom_text_repel(size = 2) +
  scale_color_manual(values = colors, na.value = "honeydew3") +
  theme_bw(base_size = 9) +
  xlab("log2foldchange") +
  ylab("log10(p-value)") +
  theme(legend.position =  "none") + # legend matches stacked bar 
  guides(color = guide_legend(na.translate = FALSE))

g

ggsave("../../figures/Fig2B-response-baseline-volcano.png", height = 4, width = 5, dpi = 500)
```

Figure 2D - Beta Diversity 

Figure 2E - Structural Zero Box plots

```{r}
counts <- counts.w %>%
  pivot_longer(!microbe, names_to = "sample", values_to = "est.reads") %>%
  filter(grepl("s__", microbe)) %>%
  mutate(microbe = str_remove(microbe, "^[a-z]__"))

r <- counts %>%
  right_join(base.samps) %>%
  left_join(demographics) %>%
  filter(Response == "Responder",
         microbe %in% (struct0.recist %>% filter(`structural_zero (Response = Non-Responder)` &
                                                 !`structural_zero (Response = Responder)`))$taxon) %>%
  select(sample, microbe, est.reads)

r.top <- r %>%
  group_by(microbe) %>%
  summarize(total.nonzero = sum(est.reads > 0),
            percent.nonzero = total.nonzero/n_distinct(sample),
            mean.counts = mean(est.reads)) %>%
  ungroup() 

nr <- counts %>%
  right_join(base.samps) %>%
  left_join(demographics) %>%
  filter(Response == "Non-Responder",
         microbe %in% (struct0.recist %>% filter(`structural_zero (Response = Responder)` &
                                                 !`structural_zero (Response = Non-Responder)`))$taxon) %>%
  select(sample, microbe, est.reads) 

nr.top <- nr %>%
  group_by(microbe) %>%
    summarize(total.nonzero = sum(est.reads > 0),
            percent.nonzero = total.nonzero/n_distinct(sample),
            mean.counts = mean(est.reads)) %>%
  ungroup()
```


```{r}
top10 <- rbind(r.top, nr.top) %>%
  filter(percent.nonzero > 0.15) %>%
  arrange(desc(mean.counts)) %>%
  slice_head(n=10)

box.in <- rbind(r, nr) %>%
  filter(microbe %in% top10$microbe) %>%
  left_join(mic.meta) %>%
  left_join(demographics) %>%
  dplyr::rename(taxon = microbe) %>%
  left_join(phyl_labels) %>%
  mutate(Phylum = ifelse(Phylum %in% phyl.ra$Phylum, Phylum, "Other"),
         taxon = gsub("_", " ", taxon),
         irAE = ifelse(irAE == "Yes", "irAE", "No irAE")) 


colors <- c("#999933","#6699CC","#44AA99")
colors <- c("darkgoldenrod2", "cyan4", "salmon2")
```

```{r}
box.in %>%
  ggplot(aes(x = taxon, y=log(est.reads), fill = Phylum)) +
  geom_boxplot(width = 0.5) +
  geom_jitter() + 
  scale_fill_manual(values = colors) +
  facet_grid(~ Response, scales = "free", space = "free") +
  theme_bw(base_size = 9) +
  theme(
    panel.spacing = unit(1, "lines"), 
    axis.text.x = element_text(angle = 45, hjust = 1),  
    strip.text = element_text(size = 9),
    legend.position = "none"
  ) +
  xlab("")

ggsave("../../figures/Fig2C-response-s0-baseline-boxplots.png", height = 3, width = 7, dpi = 300)
```

# respondersig
```{r}
rsig_plot(rsig, batch.correction = "Log.transformed")
rsig_plot(rsig.baseline, batch.correction = "Log.transformed")
```



## Figure 2F - Machine Learning 







