---
title: "modeling irAE"
author: "C. Dravillas"
date: "2025-04-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lme4)
library(broom.mixed)
library(rlist)
library(NBZIMM)
library(nlme)
library(BhGLM)
library(Metrics)
library(glmmTMB)
```

# Load data

```{r}
load("../../data/clinical.rds")
load("../../data/microbiome_metadata.rds")
load("../../data/ra-long.rds")
```

# Prepare data

```{r}
# define time points 
irAE.time <- events %>%
  filter(Event == "irAE") %>%
  mutate(irAE.day = Days) %>%
  dplyr::select(`Patient Id`, irAE.day) 

meta.irae <- mic.meta %>%
  left_join(demographics) %>%
  left_join(irAE.time) %>%
  mutate(irAE.day = ifelse(irAE.day < 0 | irAE.day > 100, NA, irAE.day),
         irAE.sample = ifelse(is.na(irAE.day), 0,
                       ifelse(abs(Days - irAE.day) <= 10, 1, 0))) %>%
  group_by(sample) %>%
  slice_max(irAE.sample, n = 1, with_ties = FALSE) %>%
  ungroup() 

model.in.ra <- ra.l %>%
  full_join(meta.irae) %>% 
  # create binary outcome var
  mutate(Days = as.integer(Days)) %>%
  rename(Patient_Id = `Patient Id`) %>%
  filter(!grepl("t__", microbe)) %>%
  pivot_wider(names_from = microbe, values_from = RelAbun, values_fill = 0) %>%
  filter(sample %in% mic.meta$sample)

microbes.ra <- colnames(model.in.ra)
microbes.ra <- microbes.ra[grepl("__", microbes.ra)]
```


microbe ~ irAE 
```{r}
capture.ZIGMM <- function(modin.dat, microbes, zero_threshold = 0.1) {
  mods.list <- list()
  zero_prop <- sapply(microbes, function(x) mean(modin.dat[[x]] == 0, na.rm = TRUE))
  
  for (x in microbes) {
    tryCatch({
      model_formula <- as.formula(paste0(x, " ~ irAE.sample"))
      
        if (zero_prop[x] >= zero_threshold) {
        # Use Zero-Inflated Gaussian Model (ZIGMM)
        model <- lme.zig(model_formula, 
                           data = modin.dat, 
                           random = ~ 1|Patient_Id, 
                           zi_fixed = ~1, 
                           zi_random = NULL
                           )
        model_type <- "ZIGMM"
      } else {
        # Use Gaussian Model (GMM)
        model <- lme(model_formula, 
                         data = modin.dat, 
                         random = ~ 1|Patient_Id
                         )
        model_type <- "GMM"
      }
      
      model_results <- broom.mixed::tidy(model)
      model_results <- model_results %>% mutate(microbe = x, model_type = model_type)
      
      mods.list[[x]] <- model_results
      
      
    }, error = function(e) {
      message("Model failed for ", x, ": ", e$message)
      mods.list[[x]] <- NULL  # Assign NULL to failed models
    })
  }
  
  mods.list.clean <- mods.list[!sapply(mods.list, is.null)]
  
  if (length(mods.list.clean) > 0) {
    mods.df <- bind_rows(mods.list.clean)
  } else {
    mods.df <- data.frame() 
  }
  
  return(mods.df)
}

gmm.out.mic <- capture.ZIGMM(model.in.ra, microbes.ra)
gmm.out.mic <- gmm.out.mic %>%
  filter(term == "irAE.sample") %>%
  mutate(padj = p.adjust(p.value, method = "bonferroni")) %>%
  left_join(pres)
```


irAE ~ microbe
With a binary outcome variable we shouldnt use gmm
We should instead be using bernoulli, does ZI exist ?
Why not just do ANCOM-BC2 again with the full sample set, split by irAE ?  
Multiple samples from patients so need mixed model

```{r}
capture.glmmTMB <- function(modin.dat, microbes, outcome = "microbe", zero_threshold = 0.1) {
  mods.list <- list()
  zero_prop <- sapply(microbes, function(x) mean(modin.dat[[x]] == 0, na.rm = TRUE))

  for (x in microbes) {
    tryCatch({
      model_formula <- as.formula(paste0("irAE.sample ~ ", x, " + (1 | Patient_Id)"))
      
      if (zero_prop[x] >= zero_threshold) {
        # Zero-inflated binomial model (if there are many zeros in the predictor)
        model <- glmmTMB(
          formula = model_formula,
          ziformula = ~1,    # Zero-inflation formula
          family = binomial,  # Binomial family for binary outcome
          data = modin.dat
        )
        model_type <- "ZIBMM"
      } else {
        # Standard binomial GLMM
        model <- glmmTMB(
          formula = model_formula,
          family = binomial,  # Binomial family for binary outcome
          data = modin.dat
        )
        model_type <- "BMM"
      }

      model_results <- broom.mixed::tidy(model)
      model_results <- model_results %>% mutate(microbe = x, model_type = model_type)
      mods.list[[x]] <- model_results

    }, error = function(e) {
      message("Model failed for ", x, ": ", e$message)
      mods.list[[x]] <- NULL  # Assign NULL to failed models
    })
  }

  mods.list.clean <- mods.list[!sapply(mods.list, is.null)]

  if (length(mods.list.clean) > 0) {
    mods.df <- bind_rows(mods.list.clean)
  } else {
    mods.df <- data.frame() 
  }

  return(mods.df)
}

gmm.out.irae <- capture.glmmTMB(model.in.ra, microbes.ra, "irae")
gmm.out.irae <- gmm.out.irae %>%
  filter(!grepl("(Intercept)", term)) %>%
  mutate(padj = p.adjust(p.value, method = "bonferroni")) %>%
  left_join(pres)
```

Nothing significant after p adjust 

```{r}
capture.glmmTMB <- function(modin.dat, microbes, outcome = "microbe", zero_threshold = 0.1) {
  mods.list <- list()
  zero_prop <- sapply(microbes, function(x) mean(modin.dat[[x]] == 0, na.rm = TRUE))

  for (x in microbes) {
    tryCatch({
      model_formula <- as.formula(paste0("irAE.sample ~ ", x, " + (1 | Patient_Id)"))
      
        model <- glmmTMB(
          formula = model_formula,
          family = binomial,  # Binomial family for binary outcome
          data = modin.dat
        )
        model_type <- "ZIBMM"
      

      model_results <- broom.mixed::tidy(model)
      model_results <- model_results %>% mutate(microbe = x, model_type = model_type)
      mods.list[[x]] <- model_results

    }, error = function(e) {
      message("Model failed for ", x, ": ", e$message)
      mods.list[[x]] <- NULL  # Assign NULL to failed models
    })
  }

  mods.list.clean <- mods.list[!sapply(mods.list, is.null)]

  if (length(mods.list.clean) > 0) {
    mods.df <- bind_rows(mods.list.clean)
  } else {
    mods.df <- data.frame() 
  }

  return(mods.df)
}

bmm.out.irae <- capture.glmmTMB(model.in.ra, microbes.ra, "irae")
bmm.out.irae <- bmm.out.irae %>%
  filter(!grepl("(Intercept)", term)) %>%
  mutate(padj = p.adjust(p.value, method = "bonferroni")) %>%
  left_join(pres)
```

