---
title: "longitudinal modeling"
author: "C. Dravillas"
date: "2025-04-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lme4)
library(broom.mixed)
library(rlist)
library(NBZIMM)
library(nlme)
# library(BhGLM)
library(Metrics)
library(glmmTMB)
```

# Load data

```{r}
load("../../data/clinical.rds")
load("../../data/microbiome_metadata.rds")
load("../../data/ra-long.rds")
load("../../data/counts-long.rds")
```

# Prepare data

```{r}
model.in.ra <- ra.l %>%
  right_join(mic.meta) %>%
  left_join(demographics) %>%
  # create binary outcome var
  mutate(response.bin = ifelse(Response == "Responder", 1, 0),
  # make days numeric
         Days = as.integer(Days)) %>%
  rename(Patient_Id = `Patient Id`) %>%
  filter(!grepl("t__", microbe)) %>%
  pivot_wider(names_from = microbe, values_from = RelAbun, values_fill = 0) %>%
  filter(sample %in% mic.meta$sample)

microbes.ra <- colnames(model.in.ra)
microbes.ra <- microbes.ra[grepl("__", microbes.ra)]

pres <- counts.l %>%
  filter(sample %in% mic.meta$sample) %>%
  group_by(Taxonomy) %>%
  summarize(pres = sum(est.reads > 0)) %>%
  mutate(microbe = str_extract(Taxonomy, "[^|]+$")) %>%
  dplyr::select(-Taxonomy) 
```


# Run ZIZMM and save output 
```{r}
capture.ZIGMM <- function(modin.dat, microbes, zero_threshold = 0.1) {
  mods.list <- list()
  zero_prop <- sapply(microbes, function(x) mean(modin.dat[[x]] == 0, na.rm = TRUE))
  
  for (x in microbes) {
    tryCatch({
      model_formula <- as.formula(paste0(x, " ~ Response*(Days + I(Days^2))"))
      
        if (zero_prop[x] >= zero_threshold) {
        # Use Zero-Inflated Gaussian Model (ZIGMM)
        model <- lme.zig(model_formula, 
                           data = modin.dat, 
                           random = ~ 1|Patient_Id, 
                           zi_fixed = ~1, 
                           zi_random = NULL
                           )
        model_type <- "ZIGMM"
      } else {
        # Use Gaussian Model (GMM)
        model <- lme(model_formula, 
                         data = modin.dat, 
                         random = ~ 1|Patient_Id
                         )
        model_type <- "GMM"
      }
      
      model_results <- broom.mixed::tidy(model)
      model_results <- model_results %>% mutate(microbe = x, model_type = model_type)
      
      mods.list[[x]] <- model_results
      
      
    }, error = function(e) {
      message("Model failed for ", x, ": ", e$message)
      mods.list[[x]] <- NULL  # Assign NULL to failed models
    })
  }
  
  mods.list.clean <- mods.list[!sapply(mods.list, is.null)]
  
  if (length(mods.list.clean) > 0) {
    mods.df <- bind_rows(mods.list.clean)
  } else {
    mods.df <- data.frame() 
  }
  
  return(mods.df)
}

gmm.out <- capture.ZIGMM(model.in.ra, microbes.ra)
gmm.out <- gmm.out %>%
  filter(term == "ResponseResponder:I(Days^2)" | term == "ResponseResponder:Days" | term == "ResponseResponder") %>%
  mutate(padj = p.adjust(p.value, method = "bonferroni")) %>%
  left_join(pres)
```

Note we expect the quadratic terms to be smaller!

# Save 

```{r}
save(gmm.out, file = "../../data/ZIGMM-model-output.rds")
```





