---
title: "table 1"
author: "Caroline Wheeler"
date: "2023-10-20"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(table1)
library(tableone)
library(gridExtra)
```

```{r}
load("../../data/clinical.rds")
load("../../data/irae.rds")
load("../../data/microbiome_metadata.rds")
```

Remove participant without baseline sample 
```{r}
baseline <- mic.meta %>%
  group_by(`Patient Id`) %>%
  arrange(Days) %>%
  slice_head(n = 1) %>%
  ungroup() %>%
  filter(abs(Days) <= 10)

demo.filt <- demographics %>%
  filter(`Patient Id` %in% baseline$`Patient Id`)
```


function to get p-value 
```{r}
pvalue <- function(x, ...) {
  x <- x[-length(x)]  # Remove "overall" group
  # Construct vectors of data y, and groups (strata) g
  y <- unlist(x)
  g <- factor(rep(1:length(x), times=sapply(x, length)))
  if (is.numeric(y)) {
    # For numeric variables, perform an ANOVA
    p <- summary(aov(y ~ g))[[1]][["Pr(>F)"]][1]
  } else {
    # For categorical variables, perform a chi-squared test of independence
    p <- chisq.test(table(y, g))$p.value
  }
  # Format the p-value, using an HTML entity for the less-than sign.
  # The initial empty string places the output on the line below the variable 
  #label.
  c("", sub("<", "&lt;", format.pval(p, digits=3, eps=0.001)))
}
```

Table 1 - strat by Response
```{r}
table1 <- table1(~ Age + Sex + Race + Treatment + Stage + irAE  | Response,
       data=demo.filt, overall="Total", extra.col=list(`P-value`=pvalue), 
       render.missing=NULL, render.continuous=c(.="Mean (SD)"))

print(table1, quote = FALSE, noSpaces = TRUE, printToggle = TRUE)
```

If we decide to make our own version 
```{r}
tab1 <- CreateTableOne(
  vars = c("Age", "Sex", "Race", "Treatment", "Stage", "irAE"),  # Variables
  strata = "Response",  # Stratification variable
  data = demo.filt,
  test = TRUE,  # Enables default p-value calculation
  addOverall = TRUE  # Add an "Overall" column
)

print(tab1)
```

Table 2 - strat by irAE
```{r}
demo.filt <- demo.filt %>%
    mutate(irAE = ifelse(irAE == "Yes", "irAE", "No irAE"))

table2 <- table1(~ Age + Sex + Race + Treatment + Stage + Response  | irAE,
       data=demo.filt, overall="Total", extra.col=list(`P-value`=pvalue), 
       render.missing=NULL, render.continuous=c(.="Mean (SD)"))

table2
```


```{r}
tab2 <- CreateTableOne(
  vars = c("Age", "Sex", "Race", "Treatment", "Stage", "Response"),  # Variables
  strata = "irAE",  # Stratification variable
  data = demo.filt,
  test = TRUE,  # Enables default p-value calculation
  addOverall = TRUE  # Add an "Overall" column
)

print(tab2)
```


