---
title: "window size"
author: "Caroline Wheeler"
date: "2023-11-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
```

load data
```{r cars}
load("../../data/events.rds")
load("../../data/microbiome_metadata.rds")
```

```{r}
irae <- events %>%
  filter(Event == "irAE") %>%
  select(`Patient Id`, Days) %>%
  rename('irae.days' = Days)

mic <- mic.meta %>%
  select(`Patient Id`, sample, Days) %>%
  rename("mic.days" = )

scan <- events %>%
  filter(Event == "CT Scan") %>%
  select(`Patient Id`, Days) %>%
  rename("scan.days" = Days)

mic.irae <- merge(mic, irae)
mic.scan <- merge(mic, scan)
```


## NYE window size code edited by CW
# number of days from when we received a microbiome sample at an irae occurence
```{r}
output <- mic.irae %>% 
  mutate(days.from.irae = abs(Days - irae.days)) %>% 
  drop_na(days.from.irae) 
```

```{r}
ggplot(output, aes(x=days.from.irae)) + geom_histogram()
```
#adding timepoints
```{r}
#define window size that will be tested
window <-seq(1,max(output$days.from.irae ))
#pre-allocate memory to store for loop output
out <- data.frame(windowsize = window, qty = NA)


for (i in window) { 
  window.test <- abs(output$days.from.irae) < i
  
  out$qty[i] <- sum(window.test) 
}
head(out)
```


```{r}
out %>% 
  ggplot(aes(x=windowsize, y = qty)) +
  geom_line() +
  theme_bw() +
  labs(x = "Window Size",
       y = "Quantity") 

ggsave(file = "../../figures/irae_windowsize.png", width = 4, height = 3)
```

```{r}
out %>% 
  ggplot(aes(x=windowsize, y = qty)) +
  geom_line() + 
  xlim(0,15) +
  ylim(0,15) +
  theme_bw() + 
    labs(x = "Window Size",
       y = "Quantity") 


ggsave(file = "../../figures/irae_windowsize_closeup.png", dev = "png", width = 4, height = 3)
```


```{r}
out %>% 
  filter(windowsize == 12)
```
```{r}
output <- mic.scan %>% 
  mutate(days.from.scan = abs(Days - scan.days)) %>% 
  drop_na(days.from.scan) 
```

```{r}
ggplot(output, aes(x=days.from.scan)) + geom_histogram()
```
```{r}
#define window size that will be tested
window <-seq(1,max(output$days.from.scan))
#pre-allocate memory to store for loop output
out <- data.frame(windowsize = window, qty = NA)


for (i in window) { 
  window.test <- abs(output$days.from.scan) < i
  
  out$qty[i] <- sum(window.test) 
}
head(out)
```

```{r}
out %>% 
  ggplot(aes(x=windowsize, y = qty)) +
  geom_line() +
  theme_bw() +
  labs(x = "Window Size",
       y = "Quantity") 
```



### Create sample categories
```{r}
mic.irae <- mic.irae %>%
  filter(abs(Days - irae.days) < 13)

mic.baseline <- mic.meta %>%
  group_by(`Patient Id`) %>% 
  filter(Days == min(Days)) 

mic.meta <- mic.meta %>%
  mutate(baseline = ifelse(sample %in% mic.baseline$sample, 1, 0),
         irAE = ifelse(sample %in% mic.irae$sample, 1, 0),
         resp.scan = NA,
         control = ifelse(irAE == 0, 1, 0))
```

