---
title: "generate-metaphlan-batch"
author: "Caroline Wheeler"
date: "8/30/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## get sample names
```{r cars}
fastq.dir1 <- "/fs/ess/PAS1695/projects/mitox/data/2022-01-31_fastqs"
fastq.dir2 <- "/fs/ess/PAS1695/projects/mitox/data/2022-08-08_fastqs"

all.files1 <- list.files(fastq.dir1, full.names = T)
all.files2 <- list.files(fastq.dir2, full.names = T)
all.files <- c(all.files1, all.files2)

snames <- gsub(".fastq.gz", "", c(list.files(fastq.dir1), list.files(fastq.dir2)))
```

qsub -t 0-{x} fastp.pbs
```{r}
fileOut<-file(paste0("/fs/ess/PAS1695/projects/mitox/scripts/batch/2024-metaphlan.pbs"))
 
writeLines(c(paste0("#PBS -N mitox-metaphlan"),
               "#PBS -l walltime=24:00:00",
               "#PBS -l nodes=1:ppn=28",
               "#PBS -j oe",
               "#PBS -m ae",
               "#PBS -A PAS1695",
               "",
               
               # List fastq file names in a way that can be indexed
               paste0("fnames=('", paste(all.files, collapse = "' '"), "')"),
               "",
               # List sample names in a way that can be indexed
               paste0("snames=('", paste(snames, collapse = "' '"), "')"),
               
               "cd /users/PAS1695/whee57/.local/bin",
               "module load python",
               "source activate metaphlan4",
               "",
          
               "metaphlan --input_type fastq --read_min_len 50 --profile_vsc --nproc 28 --vsc_out /fs/ess/PAS1695/projects/mitox/data/2024-08-30-all-fastqs_vsc/${snames[$PBS_ARRAY_INDEX]}.vsc.txt --bowtie2out /fs/ess/PAS1695/projects/mitox/data/2024-08-30-all-fastqs_bowties/${snames[$PBS_ARRAY_INDEX]}.fastq.gz.bowtie2out.txt ${fnames[$PBS_ARRAY_INDEX]} /fs/ess/PAS1695/projects/mitox/data/2024-08-30-all-fastqs_metaphlan/${snames[$PBS_ARRAY_INDEX]}.txt",
             ""
  
  ),
  
  fileOut
  )
```

retroactively get estimated counts using bowties as input 
RelAbun will be the same, just includes "estimated number of reads from the clade" 
to be used for deseq2 analysis 

generate batch job
```{r}
fileOut<-file(paste0("/fs/ess/PAS1695/projects/mitox/scripts/batch/2024-metaphlan-counts.pbs"))
 
writeLines(c(paste0("#PBS -N mitox-metaphlan-counts"),
               "#PBS -l walltime=24:00:00",
               "#PBS -l nodes=1:ppn=28",
               "#PBS -j oe",
               "#PBS -m ae",
               "#PBS -A PAS1695",
               "",

               # List sample names in a way that can be indexed
               paste0("snames=('", paste(snames, collapse = "' '"), "')"),
               
               "cd /users/PAS1695/whee57/.local/bin",
               "module load python",
               "source activate metaphlan4",
               "",
               "cd /fs/ess/PAS1695/projects/mitox/data/2024-08-30-all-fastqs_bowties",
               "",
             
               "metaphlan ${snames[$PBS_ARRAY_INDEX]}.fastq.gz.bowtie2out.txt -t rel_ab_w_read_stats -o /fs/ess/PAS1695/projects/mitox/data/2024-08-30-all-fastqs_metaphlan-counts/${snames[$PBS_ARRAY_INDEX]}.tsv --input_type bowtie2out --nproc 28",
             ""
  
  ),
  
  fileOut
  )
```

