---
title: "timeline"
author: "Caroline Wheeler"
date: '2022-12-13'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(lubridate)
library(reshape2)
```

path to t drive
```{r}
#paths.tdrive <- "T:/Labs/Spakowicz/mitox/"
paths.tdrive <- "/Volumes/spakowicz/mitox"
```

read in data 
```{r}
micSamp <- read.table(file.path(paths.tdrive, '/data/labii/mitox-samples-export_2022-10-21.tsv'), sep = '\t', header = TRUE, fill = NA)
# redcap <- read.csv(file.path(paths.tdrive, "/data/redcap/raw/2022-12-02/P841APilotStudyOfThe_DATA_2022-12-02_1235.csv"))
irAE <- readxl::read_xlsx(file.path(paths.tdrive,"Patient Logs/Clinical info/Mitoxstudy_patient_symptoms_AM_2.xlsx"))
scan_date <- readxl::read_xlsx(file.path(paths.tdrive, "/Patient Logs/Clinical info/OSU-19125_patient_progression_RECIST_MH_v3.xlsx"))
pt_log <- readxl::read_xlsx(file.path(paths.tdrive,"Patient Logs/OSU 19125 Patient Log.xlsx"), skip = 3)
```

get start and end date
```{r}
pt_log <- pt_log %>% 
  select(`Patient Id`, `C1D1 date`, `EOS Date`) %>%
  filter(!is.na(`C1D1 date`)) %>%
  mutate(`C1D1 date` = as.Date(`C1D1 date`),
         `EOS Date` = as.Date(`EOS Date`))
```

clean up microbiome data
```{r}
temp <- micSamp %>%
  # if we dont have date sample collected, we don't need the entry
  filter(!is.na(Date.Sample.Collected),
         Date.Sample.Collected != "",
         Date.Sample.Collected != "false") %>%
  select(sample_id, Type.of.Sample, Date.Sample.Collected) %>%
  # use sample_id substr instead of record_id, which is missing values
  mutate(`Patient Id` = substr(sample_id, 0, 4),
         date = as.Date(Date.Sample.Collected),
         Type.of.Sample = ifelse(Type.of.Sample == "12Wk", "12wk", Type.of.Sample)) %>%
  select(-Date.Sample.Collected) %>%
  distinct()

# multiple instances of 'Control' and 'Baseline' and 'AE'
# assuming this is intentional
micSamp <- reshape(temp, idvar = c("Patient Id", "sample_id"), timevar = "Type.of.Sample", direction = "wide")
```
         
<!-- clean up redcap  -->
<!-- ```{r} -->
<!-- redcap <- redcap %>% -->
<!--   select(mrn, patient_id) -->
<!-- ``` -->

clean up irAE dates
```{r}
irAE <- irAE %>%
  select(`Patient Id`, `Date(s)`, `irAE (AM)`) %>%
  rename(irAE = `irAE (AM)`) %>%
  fill(`Patient Id`) %>%
  mutate("irAE_date"  = openxlsx::convertToDate(`Date(s)`)) %>%
  filter(irAE == "Yes",
          !is.na(irAE_date)) %>%
  select(`Patient Id`, irAE_date)
```

clean up scan dates
dates is showing up as 1990 or 2090...
# ```{r}
# scan_date <- scan_date %>%
#   select(`12th Week Scan`, `Baseline Scan`, `Patient Id`) %>%
#   mutate(baseline_scan = openxlsx::convertToDate(!is.na(`Baseline Scan`)),
#          "12week_scan" =  openxlsx::convertToDate(!is.na(`12th Week Scan`)))%>%
#   filter(!is.na(`Patient Id`))
# ```

merge date data
```{r}
dfs <- list(pt_log, micSamp, irAE)
dates <- dfs %>% reduce(full_join, by='Patient Id')
```

calculate days
```{r}
dates <- dates %>%
  mutate("Start Study" = 0,
         "End Study" =  `EOS Date` - `C1D1 date`,
         "irAE" = irAE_date - `C1D1 date`,
         "Baseline" = date.Baseline - `C1D1 date`, 
         "Control" = date.Control - `C1D1 date`,
         "AE" = date.AE - `C1D1 date`,
         "12wk" = date.12wk - `C1D1 date`)
```

wide to long
```{r}
timepoints <- dates %>%
  select(`Patient Id`, `Start Study`,`End Study`, irAE, Baseline, Control, AE, `12wk`) %>%
  gather("Timepoint", "Date", c(`Start Study`,`End Study`, irAE, Baseline, Control, AE, `12wk`)) %>%
  distinct() %>%
  filter(!is.na(Date)) %>%
  mutate(`Sample Type` = ifelse(Timepoint %in% c("Baseline", "Control", "AE", "12wk"), "Microbiome", Timepoint))
```
 plot timeline
```{r}
timepoints %>%
  ggplot(aes(x=Date, y=`Patient Id`, col=Timepoint, group=`Patient Id`)) +
  geom_point(aes(Date, `Patient Id`, col = Timepoint, shape = `Sample Type`)) +
  geom_line() +
  scale_color_manual(values = c("darkslateblue","red3","cyan4", "darkgoldenrod2", "darkgreen", "salmon2", "cornflowerblue", "deeppink4")) +
  theme_bw() 

ggsave(file = "../figures/patient_timeline.png", dev = "png", width = 5, height = 9)
```
 


filter to desired values, rename for matching, clean up
```{r}
micSamp <- micSamp %>%
  select(sample_id, Type.of.Sample, Date.Sample.Collected) %>%
  mutate(patient_id = substr(sample_id, 0, 4)) %>%
  select(-sample_id) %>%
  rename(micSample_type = Type.of.Sample,
         micSamp_date = Date.Sample.Collected) %>%
  filter(micSamp_date != "") %>%
  filter(patient_id != "")

# tx_start <- tx_start %>%
#   select(`Date of Draw`, MRN, `Cycle #`) %>%
#   rename(tx_date = `Date of Draw`,
#          mrn = MRN,
#          cycle_num = `Cycle #`)
  
redcap <- redcap %>%
  select(mrn, patient_id)

irAE <- irAE %>%
  select(`Patient Id`, `Date(s)`, `irAE (AM)`) %>%
  rename(patient_id = `Patient Id`,
         irAE = `irAE (AM)`) %>%
  fill(patient_id) %>%
  mutate(date = openxlsx::convertToDate(`Date(s)`))

scan_date <- scan_date %>%
  select(`12th Week Scan`, `Baseline Scan`, `Patient Id`) %>%
  rename(patient_id = `Patient Id`) %>%
  mutate(baseline_scan = openxlsx::convertToDate(`Baseline Scan`),
         "12week_scan" =  openxlsx::convertToDate(`12th Week Scan`)) %>%
  filter(!is.na(patient_id))

# do we only want irAE == yes on the timeline, if so skip this

# filter to irAE == yes
irAE <- irAE %>%
  filter(irAE == "Yes",
         !is.na(date)) %>%
  select(patient_id, date) %>%
# manually fix date == "10/26/20 & 1/4/21" for M012
  add_row(patient_id = "M012", date = as.Date("2020-10-26")) %>%
  add_row(patient_id = "M012", date = as.Date("2021-01-04")) %>%
  rename("irAE_date" = date)

# unsure how to interpret 12week scan = "4/7/2022 (compares to 2/1/222)"

scan_date <- scan_date %>%
  mutate(baseline_scan = if_else(`Baseline Scan` == "5/23/2021 (CT chest)", as.Date("2021-05-23"), 
                                  if_else(`Baseline Scan` == "9/29/2021(XR)", as.Date("2021-09-29"), baseline_scan)),
         `12week_scan` = if_else(`12th Week Scan` == "1/25/22 (XR)", as.Date("2021-01-25"), 
                                 if_else(`12th Week Scan` == "4/7/2022 (compares to 2/1/222)", as.Date("2022-04-07"), `12week_scan`))) %>%
  select(patient_id, baseline_scan, `12week_scan`) 

# skip treatment start date for now 
# there are multiple dates listed as treatment start for same patient and same cycle number....


```

patient log dates
```{r}
micSamp <- micSamp %>%
  unique()

pt_log <- pt_log %>%
  select(`Patient Id`, `EOS Date`, `C1D1 date`) %>%
  rename("patient_id" = `Patient Id`) 
```

combine
```{r}
temp <- merge(irAE, pt_log, all=TRUE)
temp <- merge(temp, scan_date, all=TRUE)

```

reshape
```{r}
tx_start <- merge(tx_start, redcap, by="mrn") %>%
  mutate(event = ifelse((cycle_num == "1" | cycle_num == "1 (before C1, consented early)"), "Cycle 1 Treatment Start", 
                        ifelse((cycle_num == "2" | cycle_num == "2 Atezo"), "Cycle 2 Treatment Start", "Cycle 3 Treatment Start"))) %>%
  rename("date" = tx_date) %>%
  select(patient_id, date, event)
 
irAE$event <- "irAE"

scan_date <- scan_date %>%
  gather(key = "event", value = "date",
       baseline_scan, `12week_scan`) %>%
  filter(!is.na(date)) %>%
  mutate(event = ifelse(event == "baseline_scan", "Baseline Scan", "12 Week Scan"))

micSamp <- micSamp %>%
  rename("date" = micSamp_date,
         "event" = micSample_type) %>%
  #mutate(event = paste("Microbiome -", event))
  mutate(event = "Microbiome Sample")
```

Combine dfs w/ time points 
```{r}
timepoints_long <- rbind(irAE, tx_start, micSamp, scan_date)
timepoints_wide <- 
```

Plot timeline 
```{r}
timepoints %>%
  ggplot(aes(x=date, y=patient_id, col =event, group=patient_id)) +
  geom_point(aes(date, patient_id, col = event)) +
  geom_line() +
  theme_bw()
```

