---
title: "deseq-trial other methods"
output: html_document
date: "2024-10-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(DESeq2)
library(tidyverse)
```

## Define functions

```{r}
write_desd_pseudo <- function(tax){
  
  levs <- c("phylum", "class", "order", "family", "genus", "species")
  desd.list <- list()
  
  for (i in 1:length(levs)){
    desd <- tax %>%
      filter(grepl(paste0(substr(levs[i], 0, 1), "__"), microbe)) %>% 
      mutate(counts = counts + 1) %>%
      pivot_wider(names_from = sample, values_from = counts) %>%
      column_to_rownames("microbe") %>%
      filter_all(any_vars(. != 0))
    
    desd.list[[i]] <- desd

  }

  names(desd.list) <- levs
  return(desd.list)  
}


run_deseq_pseudo <- function(desd.list, meta, design){
  
  results.list <- list()
  
  for (i in 1:length(desd.list)) {
    desd <- desd.list[[i]]
    ord <- rownames(meta)
    desd <- desd[, ord]
    
    if(colnames(meta)[1] == "irAE"){
       dds <- DESeqDataSetFromMatrix(countData = desd,
                                  colData = meta,
                                  design = ~ irAE)
    }else{
          dds <- DESeqDataSetFromMatrix(countData = desd,
                                  colData = meta,
                                  design = ~ Response)
    }

    dds <- DESeq(dds)
    res <- results(dds)

    pd <- res$log2FoldChange

    resPlot <- data.frame(res) %>% 
      mutate(threshold = padj < 0.05,
             microbe = rownames(.),
             level = names(desd.list)[i])
    
    results.list[[i]] <- resPlot
  }

  resPlot <- do.call("rbind", results.list)
  return(resPlot)
}

write_desd_poscounts <- function(tax){
  
  levs <- c("phylum", "class", "order", "family", "genus", "species")
  desd.list <- list()
  
  for (i in 1:length(levs)){
    desd <- tax %>%
      filter(grepl(paste0(substr(levs[i], 0, 1), "__"), microbe)) %>% 
      pivot_wider(names_from = sample, values_from = counts) %>%
      column_to_rownames("microbe") %>%
      filter_all(any_vars(. != 0))
    
    desd.list[[i]] <- desd

  }

  names(desd.list) <- levs
  return(desd.list)  
}

# function to run deseq2 given a list of count tables
# maybe loop by index instead ? 
# that way you can get name
# add ifesle to handle irae vs recist!

run_deseq_poscounts <- function(desd.list, meta, design){
  
  results.list <- list()
  
  for (i in 1:length(desd.list)) {
    desd <- desd.list[[i]]
    ord <- rownames(meta)
    desd <- desd[, ord]
    
    if(colnames(meta)[1] == "irAE"){
       dds <- DESeqDataSetFromMatrix(countData = desd,
                                  colData = meta,
                                  design = ~ irAE)
    }else{
          dds <- DESeqDataSetFromMatrix(countData = desd,
                                  colData = meta,
                                  design = ~ Response)
    }

    dds <- DESeq(dds, sfType = "poscounts")
    res <- results(dds)

    pd <- res$log2FoldChange

    resPlot <- data.frame(res) %>% 
      mutate(threshold = padj < 0.05,
             microbe = rownames(.),
             level = names(desd.list)[i])
    
    results.list[[i]] <- resPlot
  }

  resPlot <- do.call("rbind", results.list)
  return(resPlot)
}
```

## COUNTS

load data
```{r}
load("../manuscript/data/counts-long.rds")
load("../manuscript/data/clinical.rds")
load("../manuscript/data/microbiome_metadata.rds")
```

create inputs for counts
```{r}
baseline <- mic.meta %>%
  group_by(`Patient Id`) %>%
  arrange(Days) %>%
  slice_head(n = 1) %>%
  ungroup()

clin <- dplyr::left_join(baseline, demographics, by = "Patient Id") %>%
  dplyr::filter(sample %in% counts.l$sample)

irae <- clin %>% 
  dplyr::select(sample, irAE) %>%
  dplyr::filter(sample %in% counts.l$sample) %>%
  distinct()

taxa_irae <- counts.l %>%
  dplyr::filter(sample %in% irae$sample)
```

counts - pseudo + poscounts

```{r}
# get list of count tables 
irae.levs <- write_desd_pseudo(taxa_irae)

# make sure order of samples matches 
irae <- irae %>% arrange(factor(sample, levels = colnames(irae.levs$phylum))) %>%
  remove_rownames() %>%
  column_to_rownames(var = "sample") %>%
  mutate(irAE = as.factor(irAE))

counts.pseudo <- run_deseq_pseudo(irae.levs, irae)

irae.levs <- write_desd_poscounts(taxa_irae)
counts.poscounts <- run_deseq_poscounts(irae.levs, irae)
```

save
```{r}
save(counts.pseudo, file = "../data/deseq_counts-pseudo.rds")
save(counts.poscounts, file = "../data/deseq_counts-poscounts.rds")
```


### RA 

load data
```{r}
load("../manuscript/data/ra-long.rds")
load("../manuscript/data/clinical.rds")
load("../manuscript/data/microbiome_metadata.rds")
```

```{r}
baseline <- mic.meta %>%
  group_by(`Patient Id`) %>%
  arrange(Days) %>%
  slice_head(n = 1) %>%
  ungroup()

clin <- dplyr::left_join(baseline, demographics, by = "Patient Id") %>%
  dplyr::filter(sample %in% ra.l$sample)

irae <- clin %>% 
  dplyr::select(sample, irAE) %>%
  dplyr::filter(sample %in% ra.l$sample) %>%
  distinct()

taxa_irae <- ra.l %>%
  dplyr::filter(sample %in% irae$sample)
```

need to estimate counts from RA 
nonzero min is 0.00017
we could scale all together, or find a scale param for each sample ?
```{r}
ggplot(taxa_irae, aes(-log10(RelAbun))) + geom_histogram(binwidth = 0.5)
ggplot(taxa_irae, aes(-log10(RelAbun*1e4))) + geom_histogram(binwidth = 0.5)
```
```{r}
taxa_irae <- taxa_irae %>%
  mutate(counts = round(RelAbun*1e4)) %>%
  select(sample, microbe, counts)
```


```{r}
# get list of count tables 
irae.levs <- write_desd_pseudo(taxa_irae)

# make sure order of samples matches 
irae <- irae %>% arrange(factor(sample, levels = colnames(irae.levs$phylum))) %>%
  remove_rownames() %>%
  column_to_rownames(var = "sample") %>%
  mutate(irAE = as.factor(irAE))

ra.pseudo <- run_deseq_pseudo(irae.levs, irae)

irae.levs <- write_desd_poscounts(taxa_irae)

ra.poscounts <- run_deseq_poscounts(irae.levs, irae)
```

```{r}
save(ra.pseudo, file = "../data/deseq_ra-pseudo.rds")
save(ra.poscounts, file = "../data/deseq_ra-poscounts.rds")
```

sample scale param
```{r}
taxa_irae <- ra.l %>%
  dplyr::filter(sample %in% irae$sample)
  
count_min <- counts.l %>%
  filter(sample %in% taxa_irae$sample,
         counts > 0) %>%
  group_by(sample) %>%
  summarize(count.min = min(counts)) %>%
  ungroup()
  
sample_mins <- taxa_irae %>%
  filter(RelAbun > 0) %>%
  group_by(sample) %>%
  summarize(min = min(RelAbun)) %>%
  ungroup() %>%
  dplyr::left_join(count_min) %>%
  mutate(scale_param = count.min/min) %>%
  ungroup()
  
taxa_irae <- taxa_irae %>%
  dplyr::left_join(sample_mins) %>%
  mutate(counts = round(RelAbun*scale_param)) %>%
  select(sample, microbe, counts)
```
```{r}
# get list of count tables 
irae.levs <- write_desd_pseudo(taxa_irae)

# make sure order of samples matches 
irae <- irae %>% arrange(factor(sample, levels = colnames(irae.levs$phylum))) %>%
  remove_rownames() %>%
  column_to_rownames(var = "sample") %>%
  mutate(irAE = as.factor(irAE))

ra.pseudo <- run_deseq_pseudo(irae.levs, irae)

irae.levs <- write_desd_poscounts(taxa_irae)

ra.poscounts <- run_deseq_poscounts(irae.levs, irae)
```

```{r}
ra.pseudo.ss <- ra.pseudo
ra.poscounts.ss <- ra.poscounts
save(ra.pseudo.ss, file = "../data/deseq_ra-pseudo-sample-scale.rds")
save(ra.poscounts.ss, file = "../data/deseq_ra-poscounts-sample-scale.rds")
```




## Try lfcshrink

```{r}
run_deseq_lcfshrink <- function(desd.list, meta, design, shrink){
  
  results.list <- list()
  
  for (i in 1:length(desd.list)) {
    desd <- desd.list[[i]]
    ord <- rownames(meta)
    desd <- desd[, ord]
    
    if(colnames(meta)[1] == "irAE"){
       dds <- DESeqDataSetFromMatrix(countData = desd,
                                  colData = meta,
                                  design = ~ irAE)
    }else{
          dds <- DESeqDataSetFromMatrix(countData = desd,
                                  colData = meta,
                                  design = ~ Response)
    }

    dds <- DESeq(dds, sfType = "poscounts")
    res <- results(dds)
    
    if(shrink == "ape"){
      res <- lfcShrink(dds=dds, coef=2, type="apeglm")
    }
    if(shrink == "ashr"){
      res <- lfcShrink(dds=dds, coef=2, type="ashr")
    }
    if(shrink == "normal"){
      res <- lfcShrink(dds=dds, coef=2, type="normal")
    }
    
    pd <- res$log2FoldChange

    resPlot <- data.frame(res) %>% 
      mutate(threshold = padj < 0.05,
             microbe = rownames(.),
             level = names(desd.list)[i])
    
    results.list[[i]] <- resPlot
  }

  resPlot <- do.call("rbind", results.list)
  return(resPlot)
}
```

lets try with counts 
```{r}
load("../manuscript/data/counts-long.rds")
load("../manuscript/data/clinical.rds")
load("../manuscript/data/microbiome_metadata.rds")

baseline <- mic.meta %>%
  group_by(`Patient Id`) %>%
  arrange(Days) %>%
  slice_head(n = 1) %>%
  ungroup()

clin <- left_join(baseline, demographics, by = "Patient Id") %>%
  dplyr::filter(sample %in% counts.l$sample)

irae <- clin %>% 
  dplyr::select(sample, irAE) %>%
  dplyr::filter(sample %in% counts.l$sample) %>%
  distinct()

taxa_irae <- counts.l %>%
  dplyr::filter(sample %in% irae$sample)

irae.levs <- write_desd_poscounts(taxa_irae)

irae <- irae %>% arrange(factor(sample, levels = colnames(irae.levs$phylum))) %>%
  remove_rownames() %>%
  column_to_rownames(var = "sample") %>%
  mutate(irAE = as.factor(irAE))
```


```{r}
counts.ape <- run_deseq_poscounts(irae.levs, irae, "ape")
counts.ash <- run_deseq_poscounts(irae.levs, irae, "ash")
counts.norm <- run_deseq_poscounts(irae.levs, irae, "normal")
```

save
```{r}
save(counts.ash, file = "../data/deseq_counts-ash.rds")
save(counts.ape, file = "../data/deseq_counts-ape.rds")
save(counts.norm, file = "../data/deseq_counts-norm.rds")
```

