---
title: "diversity calculation"
author: "Caroline Wheeler"
date: "10/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(vegan)
```

read in data
```{r}
taxa <- read.csv("../data/mpa_aggregated_long_10-5-22.csv")
```

split 'Taxonomy' column and filter to species level only
```{r}
taxa <- taxa %>%
   dplyr::select(sample, Taxonomy, RelAbun) %>%
    mutate(kingdom = gsub("(k__\\w+).*", "\\1", Taxonomy),
           phylum = ifelse(grepl("p__", Taxonomy),gsub(".*(p__\\w+).*", "\\1", Taxonomy), NA),
           order = ifelse(grepl("o__", Taxonomy),gsub(".*(o__\\w+).*", "\\1", Taxonomy), NA),
           class = ifelse(grepl("c__", Taxonomy),gsub(".*(c__\\w+).*", "\\1", Taxonomy), NA),
           family = ifelse(grepl("f__", Taxonomy),gsub(".*(f__\\w+).*", "\\1", Taxonomy), NA),
           genus = ifelse(grepl("g__", Taxonomy),gsub(".*(g__\\w+).*", "\\1", Taxonomy), NA),
           species = ifelse(grepl("s__", Taxonomy), gsub(".*(s__.*)", "\\1", Taxonomy), NA)) %>%
  filter(!is.na(species))
```

long to wide - matrix for calc
```{r}
taxa <- taxa %>%
  select(sample, species, RelAbun) %>%
  spread(key = species, value = RelAbun, fill = 0) %>%
  remove_rownames() %>%
  column_to_rownames(var = "sample")
```

# Calculate diversity
```{r}
test <- as.data.frame(diversity(taxa, index = "simpson"))
test$sample <- row.names(test)
test <- test %>%
  rename("diversity" = "diversity(taxa, index = \"simpson\")")
```

# save
```{r}
tcellDiv <- merge(tcell, test)

write.csv(tcellDiv, "../data/diversityTcell.csv", row.names = F)
```




