---
title: "irAE longitudinal models"
author: "C. Dravillas"
date: "2025-04-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(broom.mixed)
library(rlist)
library(NBZIMM)
```

```{r}
load("../manuscript/data/clinical.rds")
load("../manuscript/data/microbiome_metadata.rds")
load("../manuscript/data/counts-long.rds")
load("../manuscript/data/ra-long.rds")
load("../manuscript/data/events.rds")
```

Modeling ideas

irAE as response var, with irAE changing over time, so pt becomes irAE yes after 
having an irAE? Forever or for some amount of time?

Could also look for known signatures? 

lets so irAE yes if within 10 days so same as clutering def


```{r}
# define time points 
irAE.time <- events %>%
  filter(Event == "irAE") %>%
  mutate(irAE.day = Days) %>%
  dplyr::select(`Patient Id`, irAE.day) 

meta.irae <- mic.meta %>%
  left_join(demographics) %>%
  left_join(irAE.time) %>%
  mutate(irAE.day = ifelse(irAE.day < 0 | irAE.day > 100, NA, irAE.day),
         irAE.sample = ifelse(is.na(irAE.day), 0,
                       ifelse(abs(Days - irAE.day) <= 10, 1, 0))) %>%
  group_by(sample) %>%
  slice_max(irAE.sample, n = 1, with_ties = FALSE) %>%
  ungroup() 

pres <- counts.l %>%
  filter(sample %in% mic.meta$sample) %>%
  group_by(Taxonomy) %>%
  summarize(pres = sum(est.reads > 0)) %>%
  mutate(microbe = str_extract(Taxonomy, "[^|]+$")) %>%
  dplyr::select(-Taxonomy)

model.in <- counts.l %>%
  mutate(microbe = str_extract(Taxonomy, "[^|]+$")) %>%
  dplyr::select(-Taxonomy) %>%
  full_join(meta.irae) %>%
  # create binary outcome var
  mutate(Days = as.integer(Days)) %>%
  rename(Patient_Id = `Patient Id`) %>%
  filter(!grepl("t__", microbe)) %>%
  pivot_wider(names_from = microbe, values_from = est.reads, values_fill = 0) %>%
  filter(sample %in% mic.meta$sample)

lib.size <- counts.l %>%
  filter(Taxonomy %in% c("k__Bacteria","k__Archaea")) %>%
  group_by(sample) %>%
  summarize(library.size = sum(est.reads))

model.in <- model.in %>%
  left_join(lib.size)

model.in.ra <- ra.l %>%
  full_join(meta.irae) %>% 
  # create binary outcome var
  mutate(Days = as.integer(Days)) %>%
  rename(Patient_Id = `Patient Id`) %>%
  filter(!grepl("t__", microbe)) %>%
  pivot_wider(names_from = microbe, values_from = RelAbun, values_fill = 0) %>%
  filter(sample %in% mic.meta$sample)

microbes <- colnames(model.in)
microbes <- microbes[grepl("__", microbes)]
microbes.ra <- colnames(model.in.ra)
microbes.ra <- microbes.ra[grepl("__", microbes.ra)]
```

```{r}
test.mics <- c("f__Muribaculaceae",  "s__Bacteroides_pectinophilus", "s__Enterobacter_roggenkampii", "s__Pseudoflavonifractor_gallinarum", "g__Fournierella", "s__Blautia_sp_MCC283")
```

```{r}
# Function to fit models
fit_models <- function(x, model.in, model.in.ra) {
  model_formula_off <- as.formula(paste0("irAE.sample ~ ", x, "*Days + offset(log(library.size))"))
  model_formula <- as.formula(paste0("irAE.sample ~ ", x, "*Days"))

  models <- list(
    # FZINBMM (Counts)
    "NB" = glmm.zinb(model_formula_off, data = model.in, random = ~ 1 | Patient_Id, zi_fixed = ~1, zi_random = NULL),
    # FZINBMM w/ AR1
    "AR_NB" = glmm.zinb(model_formula_off, data = model.in, random = ~ 1 | Patient_Id, zi_fixed = ~1, zi_random = NULL, correlation = corAR1()),
    # FZINBMM w/ no offset
    "noOff_NB" = glmm.zinb(model_formula, data = model.in, random = ~ 1 | Patient_Id, zi_fixed = ~1, zi_random = NULL),
    # ZIGMM (RA)
    "Gaussian" = lme.zig(model_formula, data = model.in.ra, random = ~ 1 | Patient_Id, zi_fixed = ~1, zi_random = NULL),
    # ZIGMM w/ AR1
    "AR_Gaussian" = lme.zig(model_formula, data = model.in.ra, random = ~ 1 | Patient_Id, zi_fixed = ~1, zi_random = NULL, correlation = corAR1()),
    # ZIGMM w/ CAR1
    "CAR_Gaussian" = lme.zig(model_formula, data = model.in.ra, random = ~ 1 | Patient_Id, zi_fixed = ~1, zi_random = NULL, correlation = corCAR1()),
    # ZIGMM w/ ARMA
    "ARMA_Gaussian" = lme.zig(model_formula, data = model.in.ra, random = ~ 1 | Patient_Id, zi_fixed = ~1, zi_random = NULL, correlation = corARMA(p = 1, q = 1))
  )

  return(models)
}

# Compute model metrics
compute_metrics <- function(model, observed) {
  # mse = mean of (error)^2
  predictions <- predict(model, type = "response")
  residuals_sq <- (predictions - observed)^2
  mse <- mean(residuals_sq, na.rm = TRUE)
  rmse <- sqrt(mse)

  # define n and p 
  n <- length(observed)
  p <- length(coef(model))
  
  # variance of residuals
  sigma2 <- sum(residuals(model)^2) / (n - p)
  
  # Loglik 
  logLik <- -(n/2) * (log(2*pi*sigma2) + 1) - sum(residuals(model)^2) / (2 * sigma2)

  # number of estimate params..i think k should be 6 ?
  # + random intercept and zi intercept 
  k <- length(coef(model)) + 2
  aic <- (2 * k) - (2 * logLik)
  bic <- (log(n) * k) - (2 * logLik)

  return(c(MSE = mse, RMSE = rmse, AIC = aic, BIC = bic, LogLik = logLik))
}

# Loop over microbes
results <- list()
for (x in test.mics) {
  models <- fit_models(x, model.in, model.in.ra)

  model_metrics <- lapply(names(models), function(model_name) {
    # Use the correct observed dataset
    observed <- if (grepl("Gaussian", model_name)) model.in.ra[[x]] else model.in[[x]]
    compute_metrics(models[[model_name]], observed)
  })

  model_metrics <- do.call(rbind, model_metrics)
  rownames(model_metrics) <- names(models)

  results[[x]] <- model_metrics
  print(paste("Microbe:", x))
  print(model_metrics)
}

# Combine all results into a single data frame
final_results <- do.call(rbind, lapply(names(results), function(m) {
  cbind(Microbe = m, results[[m]])
}))

res_irAE <- as.data.frame(res_irAE)
res_irAE[, -1] <- lapply(res_irAE[, -1], as.double)

print(res_irAE)
```

Not sure this is really the model we want to use for this...
```{r}
capture.ZIGMM <- function(modin.dat, microbes, zero_threshold = 0.1) {
  mods.list <- list()
  zero_prop <- sapply(microbes, function(x) mean(modin.dat[[x]] == 0, na.rm = TRUE))
  
  for (x in microbes) {
    tryCatch({
      model_formula <- as.formula(paste0("irAE.sample ~ ", x, "*Days"))
      
        if (zero_prop[x] >= zero_threshold) {
        # Use Zero-Inflated Gaussian Model (ZIGMM)
        model <- lme.zig(model_formula, 
                           data = modin.dat, 
                           random = ~ 1|Patient_Id, 
                           zi_fixed = ~1, 
                           zi_random = NULL
                           )
        model_type <- "ZIGMM"
      } else {
        # Use Gaussian Model (GMM)
        model <- lme(model_formula, 
                         data = modin.dat, 
                         random = ~ 1|Patient_Id
                         )
        model_type <- "GMM"
      }
      
      model_results <- broom.mixed::tidy(model)
      model_results <- model_results %>% mutate(microbe = x, model_type = model_type)
      
      mods.list[[x]] <- model_results
      
      
    }, error = function(e) {
      message("Model failed for ", x, ": ", e$message)
      mods.list[[x]] <- NULL  # Assign NULL to failed models
    })
  }
  
  mods.list.clean <- mods.list[!sapply(mods.list, is.null)]
  
  if (length(mods.list.clean) > 0) {
    mods.df <- bind_rows(mods.list.clean)
  } else {
    mods.df <- data.frame() 
  }
  
  return(mods.df)
}

gmm.out <- capture.ZIGMM(model.in.ra, microbes.ra)
test <- gmm.out %>%
  filter(grepl(":Days", term)) %>%
  mutate(padj = p.adjust(p.value, method = "bonferroni")) %>%
  left_join(pres)
```


