---
title: "merge metaphlan output"
author: "Caroline Wheeler"
date: "10/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

# Load data
*Permission denied when trying to move those text files into one folder* 
```{r}
path1 <- "/fs/ess/PAS1695/projects/mitox/data/metaphlan"
path2 <- "/fs/ess/PAS1695/projects/mitox/data/metaphlan2"
path3 <- "/fs/ess/PAS1695/projects/mitox/data/problem_fastqs/metaphlan"

met1 <- list.files(path1, pattern = "txt", full.names = T)
met2 <- list.files(path2, pattern = "txt", full.names = T)
met3 <- list.files(path3, pattern = "txt", full.names = T)
met <- c(met1, met2, met3)

names1 <- list.files(path1, pattern = "txt")
names2 <- list.files(path2, pattern = "txt")
names3 <- list.files(path3, pattern = "txt")
names <- c(names1, names2, names3)
names <- substr(names, 1, nchar(names)-4)
```

```{r}
mettab.ls <- lapply(met, function(x) read.table(paste0(x),
                                                            header = F, sep = "\t", stringsAsFactors = F))

names(mettab.ls) <- names
metab.df <- bind_rows(lapply(names, function(x) mettab.ls[[x]] %>% mutate(sample = x)))

metab.df.form <- metab.df %>%
  rename("Taxonomy" = "V1",
         "TaxNum" = "V2",
         "RelAbun" = "V3",
         "Alternative.Tax" = "V4")

write.csv(metab.df.form, "../data/mpa_aggregated_long_2023-10-26.csv", row.names = F)
write.csv(metab.df.form, "/fs/ess/PAS1695/projects/mitox/data/2023-10-26_mpa_aggregated_long.csv", row.names = F)
```

