---
title: "Untitled"
author: "Rebecca Hoyd"
date: "12/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(dplyr)
library(tidyr)
library(tibble)
library(ggplot2)
```

# Load data

```{r}
readcounts <- read_excel("/fs/ess/PAS1695/projects/mitox/data/One Codex Results (2021-12-21 15_28).xlsx")
mpa <- read.csv("/fs/ess/PAS1695/projects/mitox/data/mpa_aggregated_long.csv",
                stringsAsFactors = F)

sample.translate <- read.csv("/fs/ess/PAS1695/projects/mitox/data/One Codex Sample Sheet.csv") %>%
  mutate(sampleID = Name,
         fastqID = External.Sample.ID) %>%
  select(sampleID, fastqID)
```

# Check read counts

```{r}
allreads <- as.vector(readcounts[4, 3:32])
names(allreads) <- readcounts[3, 3:32]

t(allreads) %>%
  as.data.frame() %>%
  rownames_to_column(var = "sampleID") %>%
  mutate(readCounts = as.numeric(V1),
         ) %>%
  filter(V1 < 500000)

readcntQC <- readcounts %>%
  select(-`All Samples`) %>%
  column_to_rownames(var = "Name") %>%
  t() %>%
  as.data.frame() %>%
  mutate(sampleID = `Sample Name`,
         readCounts = as.numeric(`Total Reads`),
         mappedReads = `Mapped Reads`,
         readsGrt500k = readCounts > 500000) %>%
  select(sampleID, readCounts, mappedReads, readsGrt500k)
```

# Check pca

```{r}
pca.in <- mpa %>%
  filter(grepl("s__", Taxonomy)) %>%
  select(Taxonomy, sample, RelAbun) %>%
  spread(key = Taxonomy, value = RelAbun) %>%
  column_to_rownames(var = "sample")

pca.in[is.na(pca.in)] <- 0

pca.out <- prcomp(pca.in, scale. = T)
plotdf <- pca.out$x %>%
  as.data.frame() %>%
  rownames_to_column(var = "sample")

plotdf %>%
  ggplot(aes(x = PC1, y = PC2, label = sample)) +
  geom_point() +
  geom_text() +
  theme_bw()

ggsave("../figures/QC_quick-species-PCA.png")
```

# QC function

```{r}
QC_PCA_pruning <- function(prcomp.obj){
  
  # Grab necessary info from prcomp
  tmp <- prcomp.obj$x %>%
    as.data.frame() %>%
    rownames_to_column(var = "sampleID") %>%
    select(sampleID, PC1, PC2)
  
  # Find most dense point
  kdensity<- MASS::kde2d(x = tmp$PC1, y = tmp$PC2)
  maxcell <- which(kdensity$z == max(kdensity$z), arr.ind = T)
  maxx <- kdensity$x[maxcell[1,1]]
  maxy <- kdensity$y[maxcell[1,2]]
  
  # Calculate distance to center and report distance behavior
  tmp2 <- tmp %>%
    mutate(xdist = (maxx - PC1)^2,
           ydist = (maxy - PC2)^2,
           distFromHighestDensity = sqrt(xdist + ydist))

  hist(tmp2$distFromHighestDensity)
  boxplot(tmp2$distFromHighestDensity)
  
  # Get IQR and use to determine QC pass/fail
  distsum <- summary(tmp2$distFromHighestDensity)
  IQR <- (distsum[5] - distsum[2]) * 1.5
  min.dist = distsum[2] - IQR
  max.dist = distsum[5] + IQR
  
  tmp3 <- tmp2 %>%
    mutate(PCAoutlier = ifelse(distFromHighestDensity >= min.dist & 
                             distFromHighestDensity <= max.dist, F,T)) %>%
    select(sampleID, PC1, PC2, distFromHighestDensity, PCAoutlier)
  
  return(tmp3)
}
```

```{r}
PCA.QC <- QC_PCA_pruning(pca.out) %>%
  rename(fastqID = sampleID)


table(PCA.QC$PCAoutlier)
```

```{r}
sp <- ggplot(faithful, aes(x=eruptions, y=waiting)) +
  geom_point() +
stat_density_2d(aes(fill = ..level..), geom="polygon")+
  scale_fill_gradient(low="blue", high="red")

sp

ggplot(tmp2, aes(x = PC1, y = PC2)) +
  geom_point() +
  stat_density2d(aes(fill = ..level..), geom="polygon") +
  scale_fill_gradient(low = "blue", high = "red") +
  ggsave("../figures/test_QC-with-density.png")

test <- MASS::kde2d(tmp2$PC1, tmp2$PC2)
```

# QC output table

```{r}
qc.tab <- sample.translate %>%
  left_join(readcntQC) %>%
  left_join(PCA.QC) %>%
  mutate(QCpass = ifelse(PCAoutlier == F & readsGrt500k == T, T, F)) %>%
  arrange(desc(distFromHighestDensity))

write.csv(qc.tab, "../data/QC_microbiome.csv", row.names = F) 
```

# Wait, does our sample size match? 

It does not match.
```{r}
length(readcntQC$sampleID)
length(sample.translate$sampleID)

nrow(pca.in)
```


