---
title: "patient timeline v2"
author: "Caroline Wheeler"
date: '2023-05-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(lubridate)
library(reshape2)
```

path to t drive
```{r}
#paths.tdrive <- "T:/Labs/Spakowicz/mitox/"
paths.tdrive <- "/Volumes/spakowicz/mitox"
```

read in data 
```{r}
micSamp <- read.table(file.path(paths.tdrive, '/data/labii/mitox-samples-export_2022-10-21.tsv'), sep = '\t', header = TRUE, fill = NA)
# redcap <- read.csv(file.path(paths.tdrive, "/data/redcap/raw/2022-12-02/P841APilotStudyOfThe_DATA_2022-12-02_1235.csv"))
irAE <- readxl::read_xlsx(file.path(paths.tdrive,"Patient Logs/Clinical info/Mitoxstudy_patient_symptoms_AM_2.xlsx"))
scan_date <- readxl::read_xlsx(file.path(paths.tdrive, "/Patient Logs/Clinical info/OSU-19125_patient_progression_RECIST_MH_v3.xlsx"))
pt_log <- readxl::read_xlsx(file.path(paths.tdrive,"Patient Logs/OSU 19125 Patient Log.xlsx"), skip = 3)
```

get start and end date
```{r}
pt_log <- pt_log %>% 
  select(`Patient Id`, `C1D1 date`, `EOS Date`) %>%
  filter(!is.na(`C1D1 date`),
         !is.na(`EOS Date`)) %>%
  mutate(`C1D1 date` = as.Date(`C1D1 date`),
         `EOS Date` = as.Date(`EOS Date`))
```

clean up irAE dates 
```{r}
irAE <- irAE %>%
  fill(`Patient Id`) %>%
  mutate(`Date(s)` = substr(`Date(s)`, 0, 9),
         irAE.date = ifelse(grepl("/", `Date(s)`), as.Date(`Date(s)`, "%m/%d/%Y"), 
                            openxlsx::convertToDate(`Date(s)`)),
         event.type = "irAE") %>%
  filter(`irAE (AM)` == "Yes",
          !is.na(irAE.date)) %>%
  select(`Patient Id`, event.type, irAE.date) %>%
  mutate(irAE.date = as.Date(irAE.date, origin = "1970-01-01"))
```

clean up microbiome data
```{r}
micSamp <- micSamp %>%
  # if we dont have date sample collected, we don't need the entry
  filter(!is.na(Date.Sample.Collected),
         Date.Sample.Collected != "",
         Date.Sample.Collected != "false") %>%
  select(sample_id, Type.of.Sample, Date.Sample.Collected) %>%
  # use sample_id substr instead of record_id, which is missing values
  mutate(`Patient Id` = substr(sample_id, 0, 4),
         date = as.Date(Date.Sample.Collected),
         Type.of.Sample = ifelse(Type.of.Sample == "12Wk", "12wk", Type.of.Sample)) %>%
  select(-Date.Sample.Collected) %>%
  distinct() %>%
  mutate(event.type = "Microbiome") %>%
  select(`Patient Id`, event.type, date)
```

clean up scan dates
```{r}
temp <- scan_date %>%
  filter(!is.na(`Patient ID`)) %>% 
  mutate(`Baseline Scan` = substr(`Baseline Scan`, 0, 9),
         baseline.scan = ifelse(`Baseline Scan` == "No Samples", NA,
                                ifelse(grepl("/", `Baseline Scan`), as.Date(`Baseline Scan`, "%m/%d/%Y"),
                                        openxlsx::convertToDate(`Baseline Scan`))),
         `12th Week Scan` = substr(`12th Week Scan`, 0, 9),
         
         # custom fix to specific entry that has date entered '1/25/22 (XR)'
         `12th Week Scan` = ifelse(`12th Week Scan` == "1/25/22 (", "1/25/2022", `12th Week Scan`),
         
         '12wk.scan' = ifelse((`12th Week Scan` == "	No Samples" | 
                                `12th Week Scan` == "No scan available" | 
                                `12th Week Scan` == "Not available"), NA,
                              ifelse(grepl("/", `12th Week Scan`), as.Date(`12th Week Scan`, "%m/%d/%Y"),
                                     openxlsx::convertToDate(`12th Week Scan`))),
         other.scan = `Other Scan`,
         event.type = "Scan",
         Response = Category, 
         baseline.scan =  as.Date(baseline.scan, origin = "1970-01-01"),
         `12wk.scan` =  as.Date(`12wk.scan`, origin = "1970-01-01")
         ) %>%
  select(`Patient ID`, `Patient Type`, event.type, Response, baseline.scan, `12wk.scan`, other.scan)
```


```{r}
temp <- scan_date %>%
  select(`Patient ID`, `Patient Type`, `Baseline Scan`, `12th Week Scan`, `Other Scan`, Category) %>%
  filter(!is.na(`Patient ID`)) %>% 
  mutate(`Baseline Scan` = ifelse(`Baseline Scan` == "No Samples", NA, 
                                  ifelse(`Baseline Scan` == "5/23/2021 (CT chest)", "2021-05-23",
                                         ifelse(`Baseline Scan` == "9/29/2021(XR)", "2021-09-29", 
                                              convert_to_date(`Baseline Scan`)))))



#temp$`Baseline Scan` <- convert_to_date(temp$`Baseline Scan`)

 # pivot_longer(cols = c(`Baseline Scan`, `12th Week Scan`, `Other Scan`), names_to = "scan_type", values_to = "date")
```


merge date data
```{r}
dfs <- list(pt_log, micSamp, irAE)
dates <- dfs %>% reduce(full_join, by='Patient Id')
```
