---
title: "Random Forest - Blood, Microbiome, Demographic vars"
author: "Caroline Wheeler"
date: "2/28/2024"
output: html_document
---

## code needs to be adjusted considerably, skeleton from melio 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(randomForest)
library(ROCR)
```

```{r}
load("../manuscript/data/blood.rds")
load("../manuscript/data/clinical.rds")
load("../manuscript/data/irae.rds")
load("../manuscript/data/microbiome_metadata.rds")
top.mics <- read.csv("../data/top_irae_mics.csv")
```

prep 
```{r}

```

```{r}
# Function create and test RF model #
getROC <- function(train, outcomes.train, test, outcomes.test){
  model.training <- randomForest(x = train[,-1, drop=FALSE], y = as.factor(outcomes.train$Reason.for.discontinuation))
  test.preds <- predict(model.training, test[,-1, drop=FALSE])
  
  print(model.training)
  # Check variable importance
  varImpPlot(model.training)
  # Prediction confusion matrix
  table(observed = outcomes.test$Reason.for.discontinuation, predicted = test.preds)
  
  prediction_for_roc_curve <- predict(model.training,test[,-1, drop=FALSE],type="prob")
  pred <- prediction(prediction_for_roc_curve[,2], outcomes.test$Reason.for.discontinuation, label.ordering = c("Toxicity", "Therapy complete"))
  perf <- performance(pred, "tpr", "fpr")
  
  auc_ROCR <- performance(pred, measure = "auc")
  print(auc_ROCR)
  auc <- auc_ROCR@y.values[[1]]
  print(auc)
  
  df <- data.frame(FalsePositive=c(perf@x.values[[1]]),
                   TruePositive=c(perf@y.values[[1]]))
  out <- list(auc, df)
  
  return(out)
}

```

```{r}
# Grabbing AUROC values from input models #
grabVals <- function(input){
  out <- list()
  for(i in 1:5){
    for(j in 1:5){
      out <- append(out, input[[i]][[j]][[1]])
    }
  }
  out
}
```

```{r}
# Main function call to generate RF models using 5 seeds #
kTest <- function(outcome, data, seeds){
  out <- list()
  for(i in 1:length(seeds)){
    out[[i]] <- k_validate(outcomes, data, seed = seeds[i])
  }
  out <- grabVals(out)
  
  # CW edit to function 
  out <- do.call(rbind.data.frame, out)
  colnames(out) <- c("AUC")
  out
}
```

```{r}
seed_list <- c(12345,12346,12347,12348,12349)
```

<!-- Test signature predictive power -->

<!-- # ```{r} -->
<!-- # clin_data <- clin -->
<!-- # feature_data <- feature -->
<!-- # seed <- seeds[1] -->
<!-- # ``` -->

<!-- Function for shuffling and creating training / testing groups for getROC  -->
<!-- ```{r} -->
<!-- k_validate <- function(clin_data, feature_data, seed){ -->
<!--   set.seed(seed) -->

<!--   # Grab responder samples # -->
<!--   responder_clin <- clin_data %>% -->
<!--     dplyr::filter(response == "responder") -->
<!--   # Shuffle responder samples via seed # -->
<!--   responder_clin <- responder_clin[sample(nrow(responder_clin)), ] -->

<!--   # Grab non-responder samples # -->
<!--   non_responder_clin <- clin_data %>% -->
<!--     dplyr::filter(response == "non-responder") -->
<!--   # Shuffle non-responder samples via seed # -->
<!--   non_responder_clin <- non_responder_clin[sample(nrow(non_responder_clin)), ] -->

<!--     # Creating index data frame for the R/NRs to ensure coverage for each group # -->
<!--     responder_indexes <- c(rep(1, 8), rep(2, 8), rep(3, 8), rep(4, 8), rep(5, 7)) -->
<!--     non_responder_indexes <- c(rep(1, 6), rep(2, 7), rep(3, 6), rep(4, 7), rep(5, 6)) -->
<!--     out <- list() -->

<!--     # Creating testing and training groups # -->
<!--     for(i in 1:5){ -->
<!--       rIndexes <- which(responder_indexes == i, arr.ind = TRUE) -->
<!--       nrIndexes <- which(non_responder_indexes == i, arr.ind = TRUE) -->

<!--       test.clin <- rbind(responder_clin[rIndexes, ], non_responder_clin[nrIndexes, ]) -->
<!--       train.clin <- rbind(responder_clin[-rIndexes, ], non_responder_clin[-nrIndexes, ]) -->

<!--       test.seq <- feature_data[which(feature_data$sample %in% test.clin$sample), ] -->
<!--       test.seq <- test.seq[match(test.clin$sample, test.seq$sample), ] -->

<!--       train.seq <- feature_data[which(feature_data$sample %in% train.clin$sample), ] -->
<!--       train.seq <- train.seq[match(train.clin$sample, train.seq$sample), ] -->

<!--       if(all(train.seq$sample == train.clin$sample) == FALSE){ -->
<!--         stop("Training Sample_IDs do not match") -->
<!--       } -->
<!--       if(all(test.seq$sample == test.clin$sample) == FALSE){ -->
<!--         stop("Testing Sample_IDs do not match") -->
<!--       } -->

<!--       # Creating the RF model # -->
<!--       out[[i]] <- getROC(train.seq, train.clin, test.seq, test.clin) -->
<!--     } -->


<!--   avg_auc <- lapply(out, function(x){ x[[1]]}) -->
<!--   message("\nAccuracy average: ", (rowMeans(as.data.frame(avg_auc)))) -->
<!--   return(out) -->
<!-- } -->
<!-- ``` -->

<!-- ROC function -->
<!-- ```{r} -->
<!-- # Function create and test RF model # -->
<!-- getROC <- function(train, clin.train, test, clin.test){ -->
<!--   model.training <- randomForest(x = train[,-1, drop=FALSE], y = as.factor(clin.train$response)) -->
<!--   test.preds <- predict(model.training, test[,-1, drop=FALSE]) -->

<!--   print(model.training) -->
<!--   # Check variable importance -->
<!--   varImpPlot(model.training) -->
<!--   # Prediction confusion matrix -->
<!--   table(observed = clin.test$response, predicted = test.preds) -->

<!--   prediction_for_roc_curve <- predict(model.training,test[,-1, drop=FALSE],type="prob") -->
<!--   pred <- prediction(prediction_for_roc_curve[,2], clin.test$response, label.ordering = c("non-responder", "responder")) -->
<!--   perf <- performance(pred, "tpr", "fpr") -->

<!--   auc_ROCR <- performance(pred, measure = "auc") -->
<!--   print(auc_ROCR) -->
<!--   auc <- auc_ROCR@y.values[[1]] -->
<!--   print(auc) -->

<!--   df <- data.frame(FalsePositive=c(perf@x.values[[1]]), -->
<!--                    TruePositive=c(perf@y.values[[1]])) -->
<!--   out <- list(auc, df) -->

<!--   return(out) -->
<!-- } -->

<!-- ``` -->

<!-- ```{r} -->
<!-- # Grabbing AUROC values from input models # -->
<!-- grabVals <- function(input){ -->
<!--   out <- list() -->
<!--   for(i in 1:5){ -->
<!--     for(j in 1:5){ -->
<!--       out <- append(out, input[[i]][[j]][[1]]) -->
<!--     } -->
<!--   } -->
<!--   out -->
<!-- } -->
<!-- ``` -->

<!-- # ```{r} -->
<!-- # clin <- response -->
<!-- # feature <- microSigs -->
<!-- # seeds <- seed_list -->
<!-- # ``` -->

<!-- ```{r} -->
<!-- # Main function call to generate RF models using 5 seeds # -->
<!-- kTest <- function(clin, feature, seeds){ -->
<!--   out <- list() -->
<!--   for(i in 1:length(seeds)){ -->
<!--     out[[i]] <- k_validate(clin, feature, seed = seeds[i]) -->
<!--   } -->
<!--   out <- grabVals(out) -->

<!--   # CW edit to function  -->
<!--   out <- do.call(rbind.data.frame, out) -->
<!--   colnames(out) <- c("AUC") -->
<!--   out -->
<!-- } -->
<!-- ``` -->

<!-- ```{r} -->
<!-- seed_list <- c(12345,12346,12347,12348,12349) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- g <- microSigs %>% select(sample, gopa) -->
<!-- gopa_auc <- kTest(response, g, seed_list)  -->
<!-- gopa_auc$signature <- "gopa" -->

<!-- f <- microSigs %>% select(sample, frankel) -->
<!-- frankel_auc <- kTest(response, f, seed_list) -->
<!-- frankel_auc$signature <- "frankel" -->

<!-- m <- microSigs %>% select(sample, matson) -->
<!-- matson_auc <- kTest(response, m, seed_list) -->
<!-- matson_auc$signature <- "matson" -->

<!-- w <- microSigs %>% select(sample, wind) -->
<!-- wind_auc <- kTest(response, w, seed_list) -->
<!-- wind_auc$signature <- "wind" -->

<!-- alpha_auc <- kTest(response, alpha, seed_list) -->
<!-- alpha_auc$signature <- "alpha diversity" -->

<!-- genus_auc <- kTest(response, genus, seed_list) -->
<!-- genus_auc$signature <- "genus" -->

<!-- # paa_auc <- kTest(response, paa, seed_list) -->
<!-- # paa_auc$signature <- "paa" -->
<!-- ``` -->

<!-- prep for boxplot -->
<!-- ```{r} -->
<!-- aucs <- rbind(matson_auc, gopa_auc, frankel_auc, wind_auc, genus_auc, alpha_auc) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- plot <- ggplot(data=aucs, mapping=aes(x=reorder(signature, AUC), y=AUC, col=signature)) + -->
<!--   geom_boxplot() + -->
<!--   geom_jitter(size=0.4, alpha=0.9) + -->
<!--   theme_bw() -->

<!-- plot -->
<!-- ``` -->

<!-- save -->
<!-- ```{r} -->
<!-- ggsave(plot = plot, file = "../figures/sig_boxplot.png", dev = "png", width = 6, height = 5, dpi = 600) -->
<!-- ``` -->
