---
title: "sample match"
author: "Caroline Wheeler"
date: '2022-08-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(tidyverse)
```

read in keys
```{r}
mdsc <- readxl::read_xlsx(file.path(paths$oneDrive, "/data/MDSC/mitox_pt_ID_MDSC.xlsx")) %>%
  select(-`...1`) %>%
  rename(record_id = "MitoxPatient ID")

timepoints <- read.csv(file.path(paths$oneDrive, "/data/Labii Export/labii_samples_export_2022-08-19.tsv"), sep = "\t") 

samps <- read_xlsx( file.path(paths$oneDrive, "/data/onecodex/2021-10-27_mitox_One Codex Sample Registration.xlsx")) %>%
  select("Barcode ID", "Name") %>%
  mutate(sample_id = gsub("_", ".", Name)) %>%
  mutate(sample_id = gsub(" ", ".", sample_id)) %>%
  select(-Name) %>%
  rename("sample" = "Barcode ID")

samps2 <- read_xlsx( file.path(paths$oneDrive, "/data/onecodex/2022-07-27_mitox_remaining_One Codex Sample Registration.xlsx")) %>%
  select("Barcode ID", "Name") %>%
  mutate(sample_id = gsub("_", ".", Name)) %>%
  mutate(sample_id = gsub(" ", ".", sample_id)) %>%
  select(-Name) %>%
  rename("sample" = "Barcode ID")

samps <- rbind(samps, samps2)
```
read in 
```{r}
adj <- readxl::read_xlsx("/Volumes/spakowicz/mitox/data/Burd_clinicdata/Burd_NanostringSummary_June2022.xlsx", sheet = "ALL ADJ DATA") %>%
  select(Sample) %>%
  mutate(Category = "adjuvant")

dis <- readxl::read_xlsx("/Volumes/spakowicz/mitox/data/Burd_clinicdata/Burd_NanostringSummary_June2022.xlsx", sheet = "MET DIS. DATA") %>%
  select(Sample) %>%
  mutate(Category = "dis")


val <- readxl::read_xlsx("/Volumes/spakowicz/mitox/data/Burd_clinicdata/Burd_NanostringSummary_June2022.xlsx", sheet = "MET VAL. DATA") %>%
    select(Sample) %>%
  mutate(Category = "val")


ipi_nivo_met <- readxl::read_xlsx("/Volumes/spakowicz/mitox/data/Burd_clinicdata/Burd_NanostringSummary_June2022.xlsx", sheet = "IPI NIVO MET DATA") %>%
    select(Sample) %>%
  mutate(Category = "ipi_nivo_met")

  
temp <- rbind(adj, dis, val, ipi_nivo_met) %>%
  mutate(Sample = gsub(" ", "-", Sample)) %>%
  filter(!is.na(Sample)) %>%
  rename("MDSC #" = Sample)
```


fix time point table
```{r}
timepoints <- timepoints %>%
  select(sample_id, record_id, Type.of.Sample, Date.Sample.Collected) %>%
  filter(!(is.na(sample_id) | sample_id==""), ) %>%
 # mutate(record_id = ifelse(record_id=="", substr(sample_id, 0, 4), record_id)) %>%
  filter(!(is.na(Type.of.Sample) | Type.of.Sample==""), ) %>%
  mutate(sample_id = gsub(" ", ".", sample_id)) %>%
  mutate(Type.of.Sample = ifelse(Type.of.Sample == "12Wk", "12wk", Type.of.Sample))

# fix two sample ID's entered wrong
timepoints <- timepoints %>%
  mutate(sample_id = ifelse(sample_id == "4028.201204.1", "M028.201204.1", 
                            ifelse(sample_id == "4028.201204.2", "M028.201204.2", sample_id)))
```

combine
left with 106 samples - same number as the first batch of metaphlan fastqs
need to confirm that they match
```{r}
samples <- left_join(samps, timepoints) %>%
  mutate(record_id = ifelse((record_id=="" | is.na(record_id)), substr(sample_id, 0, 4), record_id))

samples <- left_join(samples, mdsc)
adj_count <- merge(samples, temp)

table(adj_count$Category)
```

save datafram
```{r}
write.csv(samples, "../data/mitox_sample_matching.csv")
```


find dropped samples - not present in timepoints
```{r}
samps %>% filter(!(`Barcode ID` %in% test$`Barcode ID`))
```
```{r}
#samples$Type.of.Sample <- factor(samples$Type.of.Sample, levels = c("Baseline", "12wk", "Control", "AE", NA))

samples %>%
  ggplot(aes(x=Date.Sample.Collected, y=record_id, color = Type.of.Sample)) + 
  geom_point() +
  xlab("Timepoint") +
  ylab("Record ID") +
  theme_bw() +
  scale_y_discrete(limits=rev) +
  theme(legend.position = "none")

#ggsave("../figures/mitox_sample_timeline.png", height = 5, width = 3, dpi=300)
```

