---
title: "tcellsen_control"
author: "Caroline Wheeler"
date: '2022-10-28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(lmtest)
```

read in data
```{r}
### MITOX ###
clin_met <- read.csv("/Volumes/spakowicz/mitox/Patient Logs/Clinical info/Patient Data 7-1-22_Met_Datasheet.csv", header = TRUE, skip = 1) %>%
  select("Coded.Sample..", Cohort, "Age.When.Sample.Drawn..years.", "Sex..M.F.", "Smoker..current.former.non.secondhand.", "BMI..kg.m2.") %>%
  rename(MDSC = "Coded.Sample..",
         Category = Cohort,
         Age = "Age.When.Sample.Drawn..years.",
         Sex = "Sex..M.F.",
         Smoking_Status = "Smoker..current.former.non.secondhand.",
         BMI = "BMI..kg.m2.") %>%
  drop_na() %>%
  mutate(MDSC = strtrim(MDSC, 9),
         #manually fix MDSC # that has space in the front
         MDSC = ifelse(MDSC == " MDSC-182", "MDSC-182", MDSC))

clin_adj <- read.csv("/Volumes/spakowicz/mitox/Patient Logs/Clinical info/Patient Data 7-1-22_Adj_Datasheet.csv", header = TRUE, skip = 1)  %>%
  select("Coded.Sample..", Cohort, "Age.When.Sample.Drawn..years.", "Sex..M.F.","Smoker..current.former.never.second.hand.", "BMI..kg.m2.")  %>%
  rename(MDSC = "Coded.Sample..",
         Category = Cohort,
         Age = "Age.When.Sample.Drawn..years.",
         Sex = "Sex..M.F.",
         Smoking_Status = "Smoker..current.former.never.second.hand.",
         BMI = "BMI..kg.m2.") %>%
  drop_na() %>%
  mutate(MDSC = strtrim(MDSC, 9)) %>%
  filter(MDSC != "")

clin <- rbind(clin_adj, clin_met)

mitox <- read.csv("../data/diversityTcell.csv") %>%
  rename(MDSC = "MDSC..")

rm(clin_adj, clin_met)
```

```{r}
### FITNESS ###

# multiple diversity and tcellsen values for each patient
fitnessDiv <- read.csv("/Users/wheeler.1017/Documents/Github/fitness/exploratory/data/OC_simpson-diversity.csv")
fitnessTcell <- read.csv("/Users/wheeler.1017/Documents/Github/fitness/exploratory/data/Tcell-senescence.csv")

# to consult for matching purposes
fitnessKey <- readxl::read_xlsx("/Users/wheeler.1017/Documents/GitHub/fitness/exploratory/data/cycle_study-visit-tracker_v3.xlsx")
```

fitness sample matching
```{r}
fitnessTcell <- fitnessTcell %>%
  filter(patient.id %in% fitnessDiv$patient.id)

# matching cycle and study visits - there should be 58 total matching 
fitnessDiv <- fitnessDiv %>%
  filter(patient.id %in% fitnessTcell$patient.id) %>%
  mutate(visit = ifelse(redcap_event_name == "study_visit_1_arm_2", "SV1", 
                        ifelse(redcap_event_name == "study_visit_2_arm_2", "SV2",
                               ifelse(redcap_event_name == "study_visit_3_arm_2", "SV3",
                                      ifelse(redcap_event_name == "study_visit_4_arm_2", "SV4", NA))))) %>%
  # manual mutates
  mutate(visit = ifelse((patient.id == "4015" & redcap_event_name == "cycle_visit_5_arm_2"),"SV2" ,visit)) %>%
  mutate(visit = ifelse((patient.id == "4017" & redcap_event_name == "cycle_visit_5_arm_2"),"SV2" ,visit)) %>%
  mutate(visit = ifelse((patient.id == "4017" & redcap_event_name == "cycle_visit_8_arm_2"),"SV3" ,visit)) 
           

# need to do a lot manually 
fitness <- merge(fitnessDiv, fitnessTcell, by=c("patient.id","visit"))

```

```{r}
fitness_base <- fitness %>%
  filter(visit == "SV1") %>%
  select(patient.id, Tcell.Senescence, Simpson.div) %>%
  rename("diversity" = "Simpson.div")

fitnessClin <- read.csv("/Volumes/spakowicz/fitness/data/derived/clinical-OC-matched_resolved_limited.csv") %>%
  filter(!is.na(study_enrollment_complete)) %>%
  select(patient.id, age, sex) %>%
    rename(Age = age,
           Sex = sex)

missing_clin <- read.csv("/Users/wheeler.1017/Desktop/fitness_bmi-tobacco-baseline.csv") %>%
  rename(patient.id = "sid_2",
         Smoking_Status = tobacco,
         BMI = bmi)

fitnessClin <- merge(fitnessClin, missing_clin)

# Note BMI is missing from all fitness samples listed here

fitness_base <- merge(fitness_base, fitnessClin)
fitness <- merge(fitness, fitnessClin)
```


# filter to baseline
```{r}
baseline <- mitox %>%
  filter(Type.of.Sample == "Baseline")
```

combine with clin vars
```{r}
# 3 samples are dropped - figure this out later?
baseClin <- merge(baseline, clin, by="MDSC")

#filter to metastatic
baseClin_mitoxMet <- baseClin %>%
    filter(Category.x != "adjuvant")
```

tcell.sen ~ alpha.div + age (+ bmi + sex + smoking status)
```{r}
corr <- lm(Tcell.Senescence ~ diversity + Age + Sex + BMI, data = baseClin)

summary(corr)
```

mitox baseline met only
```{r}
corr <- lm(Tcell.Senescence ~ diversity + Age, data = baseClin_mitoxMet)

summary(corr)
```

fitness SV1 
```{r}
corr <- lm(Tcell.Senescence ~ diversity, data = fitness_base)

summary(corr)
```


fitness SV1 + age + sex
```{r}
corr <- lm(Tcell.Senescence ~ diversity + Age + Sex, data = fitness_base)

summary(corr)
```

```{r}
fitness_temp <- fitness_base %>%
  select("Tcell.Senescence","diversity","Age","Sex", "BMI")

fitness_temp$Cancer <- "lung"
fitness_temp <- fitness_temp %>%
  mutate(Sex = ifelse(Sex == 1, "M", "F"))

mitox_temp <- baseClin_mitoxMet %>%
  select("Tcell.Senescence","diversity","Age","Sex","BMI")
mitox_temp$Cancer <- "melanoma"

combo <- rbind(fitness_temp, mitox_temp)
```


fitness + mitox (ALL baseline)
```{r}
corr <- lm(Tcell.Senescence ~ diversity + Cancer + Sex + Age , data = combo)

summary(corr)
```


```{r}
fitness %>% 
  mutate(patient.id = as.factor(patient.id)) %>%
  ggplot(aes(x=Tcell.Senescence, y=Simpson.div)) +
  geom_point(aes(color = patient.id)) 
```

Controlling for confounding
```{r}
fitnessControl <- merge(fitness, fitnessClin, all = TRUE) %>%
  filter(!is.na(Tcell.Senescence)) %>%
  filter(!is.na(Age))

corr <- lm(Tcell.Senescence ~ Simpson.div + Age + Sex, data = fitnessControl)
Res <- residuals(corr) 

fitnessControl$res <- Res

fitnessControl %>%
  mutate(patient.id = as.factor(patient.id)) %>%
  ggplot(aes(x = res, y= Simpson.div)) +
  geom_point(aes(color = patient.id)) +
  geom_smooth(method = "lm")
```

