---
title: "power calc examples"
author: "Caroline Wheeler"
date: "2024-07-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(mixedpower)
```

```{r cars}
load("/Users/wheeler.1017/Desktop/Yan_et_al.RData")
```

```{r}
library(lme4)
#  LMM including word length and word complexity as fixed effects and random intercepts for subject and sentence
FLPmodel <- lmer(flp ~ word_length * complexity + (1|subject) + (1|sentence),
                 data = YanData)

summary(FLPmodel, corr = F) # let's have a look!
```

```{r}
model <- FLPmodel # which model do we want to simulate power for?
data <- YanData # data used to fit the model
fixed_effects <- c("word_length", "complexity") # all fixed effects specified in FLPmodel
simvar <- "subject"
```

```{r}
steps <- c(20, 30, 40, 50, 60) # which sample sizes do we want to look at?
critical_value <- 2 # which t/z value do we want to use to test for significance?
n_sim <- 1000 # how many single simulations should be used to estimate power?
```

```{r}
power_FLP <- mixedpower(model = FLPmodel, data = YanData,
                        fixed_effects = c("word_length", "complexity"),
                        simvar = "subject", steps = c(20,30,40,50,60),
                        critical_value = 2, n_sim = 1000)
```

```{r}
power_FLP
```


```{r}
SESOI <- c(3.66, 0.75, -0.065, 0.09) # specify SESOI

power_SESOI <- mixedpower(model = FLPmodel, data = YanData,
                              fixed_effects = c("word_length", "complexity"),
                              simvar = "subject", steps = c(20,30,40,50,60),
                              critical_value = 2, n_sim = 1000,
                              SESOI = SESOI, databased = T)

```
```{r}
power_SESOI
```

```{r}
multiplotPower(power_SESOI)
```

```{r}
FLPmodel_extended <- extend(FLPmodel, along="subject", n = 60) #extend data set to include 60 participants
```

```{r}
powerC <- powerCurve(fit = FLPmodel_extended, test = fixed("complexity"), along = "subject",
                      breaks = c(20, 30, 40, 60))
```

```{r}
print(powerC)
```

```{r}
fixef(FLPmodel)["complexity"] <- -0.065
```


