---
title: "format"
author: "Caroline Wheeler"
date: '2022-11-15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
```

read in mitox data
```{r}
clin_met <- read.csv("/Volumes/spakowicz/mitox/Patient Logs/Clinical info/Burd-other-data/Patient Data 7-1-22_Met_Datasheet.csv", header = TRUE, skip = 1) %>%
  select("Coded.Sample..", Cohort, "Age.When.Sample.Drawn..years.", "Sex..M.F.", "Smoker..current.former.non.secondhand.", "BMI..kg.m2.") %>%
  rename(MDSC = "Coded.Sample..",
         Category = Cohort,
         Age = "Age.When.Sample.Drawn..years.",
         Sex = "Sex..M.F.",
         Smoking_Status = "Smoker..current.former.non.secondhand.",
         BMI = "BMI..kg.m2.") %>%
  drop_na() %>%
  mutate(MDSC = strtrim(MDSC, 9),
         #manually fix MDSC # that has space in the front
         MDSC = ifelse(MDSC == " MDSC-182", "MDSC-182", MDSC))

clin_adj <- read.csv("/Volumes/spakowicz/mitox/Patient Logs/Clinical info/Burd-other-data/Patient Data 7-1-22_Adj_Datasheet.csv", header = TRUE, skip = 1)  %>%
  select("Coded.Sample..", Cohort, "Age.When.Sample.Drawn..years.", "Sex..M.F.","Smoker..current.former.never.second.hand.", "BMI..kg.m2.")  %>%
  rename(MDSC = "Coded.Sample..",
         Category = Cohort,
         Age = "Age.When.Sample.Drawn..years.",
         Sex = "Sex..M.F.",
         Smoking_Status = "Smoker..current.former.never.second.hand.",
         BMI = "BMI..kg.m2.") %>%
  drop_na() %>%
  mutate(MDSC = strtrim(MDSC, 9)) %>%
  filter(MDSC != "")

clin <- rbind(clin_adj, clin_met)

mitox <- read.csv("../data/diversityTcell.csv") %>%
  rename(MDSC = "MDSC..")
```

read in fitness data
```{r}
# multiple diversity and tcellsen values for each patient
fitnessDiv <- read.csv("/Users/wheeler.1017/Documents/Github/fitness/exploratory/data/OC_simpson-diversity.csv")
fitnessTcell <- read.csv("/Users/wheeler.1017/Documents/Github/fitness/exploratory/data/Tcell-senescence.csv")

# to consult for matching purposes
fitnessKey <- readxl::read_xlsx("/Users/wheeler.1017/Documents/GitHub/fitness/exploratory/data/cycle_study-visit-tracker_v3.xlsx")

fitnessClin <- read.csv("/Volumes/spakowicz/fitness/data/derived/clinical-OC-matched_resolved_limited.csv") %>%
  filter(!is.na(study_enrollment_complete)) %>%
  select(patient.id, age, sex) %>%
    rename(Age = age,
           Sex = sex)

missing_clin <- read.csv("/Users/wheeler.1017/Desktop/fitness_bmi-tobacco-baseline.csv") %>%
  rename(patient.id = "sid_2",
         Smoking_Status = tobacco,
         BMI = bmi)
```

fitness sample matching
```{r}
fitnessTcell <- fitnessTcell %>%
  filter(patient.id %in% fitnessDiv$patient.id)

# matching cycle and study visits - there should be 58 total matching 
fitnessDiv <- fitnessDiv %>%
  filter(patient.id %in% fitnessTcell$patient.id) %>%
  mutate(visit = ifelse(redcap_event_name == "study_visit_1_arm_2", "SV1", 
                        ifelse(redcap_event_name == "study_visit_2_arm_2", "SV2",
                               ifelse(redcap_event_name == "study_visit_3_arm_2", "SV3",
                                      ifelse(redcap_event_name == "study_visit_4_arm_2", "SV4", NA))))) %>%
  # manual mutates
  # FF05466567 is SV3 
  mutate(visit = ifelse((patient.id == "4015" & redcap_event_name == "cycle_visit_5_arm_2"),"SV2" ,visit)) %>%
  mutate(visit = ifelse((patient.id == "4017" & redcap_event_name == "cycle_visit_5_arm_2"),"SV2" ,visit)) %>%
  mutate(visit = ifelse((patient.id == "4017" & redcap_event_name == "cycle_visit_8_arm_2"),"SV3" ,visit)) 
           

fitness <- merge(fitnessDiv, fitnessTcell, by=c("patient.id","visit"))
```

fitness set up
```{r}
fitnessClin <- merge(fitnessClin, missing_clin)
fitness <- merge(fitness, fitnessClin) %>%
  select(-redcap_event_name)
```

```{r}
fitness <- fitness %>%
  rename("diversity" = Simpson.div) %>%
  select(patient.id, sample, visit, Tcell.Senescence, diversity, Age, Sex, BMI, Smoking_Status)
```

write fitness CSV
fill in file path
```{r}
write.csv(fitness, "fitness_tcellsen_div.csv")
```

mitox set up
```{r}
#clin <- clin %>% select(-Category)
mitox <- merge(mitox, clin, by="MDSC") %>%
  rename(patient.id = MDSC,
         visit = Type.of.Sample)
```

```{r}
mitox <- mitox %>%
  rename("drug" = Category.x,
         "drugFull" = Category.y) %>%
  select(patient.id, sample, visit, Tcell.Senescence, diversity, Age, Sex, BMI, Smoking_Status, drug, drugFull)
```

write mitox CSV
fill in file path
```{r}
write.csv(mitox, "mitox_tcellsen_div.csv")
```

