---
title: "Random Forest - Blood, Microbiome, Demographic vars"
author: "Caroline Wheeler"
date: "2/28/2024"
output: html_document
---

## code needs to be adjusted considerably, skeleton from melio 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(randomForest)
library(ROCR)
```

```{r}
load("../manuscript/data/blood.rds")
load("../manuscript/data/clinical.rds")
load("../manuscript/data/microbiome_metadata.rds")
top.mics <- read.csv("../data/top_irae_mics.csv")
```

```{r Prepare Datasets}
blood <- mic.meta %>%
  left_join(blood) %>%
  filter(sample %in% top.mics$sample) %>%
  select(-`Patient Id`, -Days, -sample_id) %>%
  filter(!is.na(AHR))

mics <- top.mics %>%
  filter(sample %in% blood$sample)

blood.mics <- top.mics %>%
  left_join(mic.meta) %>%
  left_join(blood) %>%
  select(-`Patient Id`, -Days, -sample_id) %>%
  filter(!is.na(AHR)) %>% 
  arrange(sample)

dem <- demographics %>%
  select(`Patient Id`, Sex, Age, Stage)

blood.mics.dem <- top.mics %>%
  left_join(mic.meta) %>%
  left_join(blood) %>%
  left_join(dem) %>%
  select(-`Patient Id`, -Days, -sample_id) %>%
  filter(!is.na(AHR)) %>% 
  arrange(sample) %>%
  mutate(Sex = ifelse(Sex == "Male", 1, 0))

#blood.dem <- 
#mics.dem <-

irae <- mic.meta %>%
  filter(sample %in% top.mics$sample) %>%
  left_join(demographics) %>%
  select(sample, irAE) %>%
  filter(sample %in% blood.mics$sample) %>%
  arrange(sample)
```

```{r Necessary Functions}

# Main function call to generate RF models using 5 seeds #
kTest <- function(clin, feature, seeds){
  out <- list()
  for(i in 1:length(seeds)){
    out[[i]] <- k_validate(clin, feature, seed = seeds[i])
  }
  out <- grabVals(out)
  out
}

# Shuffling and creating training / testing groups for getROC #
k_validate <- function(clin_data, feature_data, seed){
  set.seed(seed)
  
  # Grab irae samples #
  irae_clin <- clin_data %>%
    dplyr::filter(irAE == "Yes")
  # Shuffle irae samples via seed #
  irae_clin <- irae_clin[sample(nrow(irae_clin)), ]
  
  # Grab non-irae samples #
  non_irae_clin <- clin_data %>%
    dplyr::filter(irAE == 'No')
  # Shuffle non-irae samples via seed #
  non_irae_clin <- non_irae_clin[sample(nrow(non_irae_clin)), ]

    # Creating index data frame for the R/NRs to ensure coverage for each group #
    # indexes need to total number of samples 
    irae_indexes <- c(rep(1, 4), rep(2, 4), rep(3, 4))
    non_irae_indexes <- c(rep(1, 7), rep(2, 7), rep(3, 8))
    out <- list()
    
    # Creating testing and training groups #
    for(i in 1:3){
      rIndexes <- which(irae_indexes == i, arr.ind = TRUE)
      nrIndexes <- which(non_irae_indexes == i, arr.ind = TRUE)
      
      test.clin <- rbind(irae_clin[rIndexes, ], non_irae_clin[nrIndexes, ])
      train.clin <- rbind(irae_clin[-rIndexes, ], non_irae_clin[-nrIndexes, ])
      
      test.seq <- feature_data[which(feature_data$sample %in% test.clin$sample), ]
      test.seq <- test.seq[match(test.clin$sample, test.seq$sample), ]
      
      train.seq <- feature_data[which(feature_data$sample %in% train.clin$sample), ]
      train.seq <- train.seq[match(train.clin$sample, train.seq$sample), ]
      
      if(all(train.seq$sample == train.clin$sample) == FALSE){
        stop("Training samples do not match")
      }
      if(all(test.seq$sample == test.clin$sample) == FALSE){
        stop("Testing samples do not match")
      }
      
      # Creating the RF model #
      out[[i]] <- getROC(train.seq, train.clin, test.seq, test.clin)
    }
  
  
  avg_auc <- lapply(out, function(x){ x[[1]]})
  message("\nAccuracy average: ", (rowMeans(as.data.frame(avg_auc))))
  return(out)
}

# Grabbing AUROC values from input models #
grabVals <- function(input){
  out <- list()
  for(i in 1:5){
    for(j in 1:3){
      out <- append(out, input[[i]][[j]][[1]])
    }
  }
  out
}

# Function create and test RF model #
getROC <- function(train, clin.train, test, clin.test){
  model.training <- randomForest(x = train[,-1, drop=FALSE], y = as.factor(clin.train$irAE))
  test.preds <- predict(model.training, test[,-1, drop=FALSE])
  
  print(model.training)
  # Check variable importance
  varImpPlot(model.training)
  # Prediction confusion matrix
  table(observed = clin.test$irAE, predicted = test.preds)
  
  prediction_for_roc_curve <- predict(model.training,test[,-1, drop=FALSE],type="prob")
  pred <- prediction(prediction_for_roc_curve[,2], clin.test$irAE, label.ordering = c("No", "Yes"))
  perf <- performance(pred, "tpr", "fpr")
  
  # auc_ROCR <- performance(pred, measure = "auc")
  # print(auc_ROCR)
  # auc <- auc_ROCR@y.values[[1]]
  # print(auc)
  
  #balanced AUC version
  b.auc_ROCR <- performance(pred, "sens", "spec")
  auc <- max((b.auc_ROCR@x.values[[1]] + b.auc_ROCR@y.values[[1]]) / 2)
  print(auc)
  
  df <- data.frame(FalsePositive=c(perf@x.values[[1]]),
                   TruePositive=c(perf@y.values[[1]]))
  out <- list(auc, df)
  
  return(out)
}
```

```{r Test Signatures}
seed_list <- c(12345,12346,12347,12348,12349)

# blood alone 
blood.auc <- kTest(irae, blood, seed_list)
#blood.auc$Group <- "Blood"

# mics alone
mics.auc <- kTest(irae, mics, seed_list)
#mics.auc$Group <- "Microbes"

# blood + mics
blood.mics.auc <- kTest(irae, blood.mics, seed_list)
#blood.mics.auc$Group <- "Blood + Microbes"

# blood + demographics + mics
blood.mics.dem.auc <- kTest(irae, blood.mics.dem, seed_list)

# blood + demographics
# blood + demographics + mics
# demographics + mics
```

```{r Shape Model Results}
Results <- data.frame(
  unlist(blood.auc),
  unlist(mics.auc),
  unlist(blood.mics.auc),
  unlist(blood.mics.dem.auc)
)
colnames(Results) <- c("Blood", 
                       "Microbes", 
                       "Blood + Microbes",
                       "Blood + Microbes\n + Demographics")

Results <- tidyr::pivot_longer(Results, cols = dplyr::everything(), names_to = "Model", values_to = "AUROC")
Means <- Results %>%
  dplyr::group_by(Model) %>%
  dplyr::mutate(Model_Mean = mean(AUROC)) %>%
  dplyr::select(Model, Model_Mean) %>%
  dplyr::distinct() %>%
  dplyr::arrange(desc(Model_Mean))
Means$Model <- factor(Means$Model, levels = unique(Means$Model))
mean_order <- rev(levels(Means$Model))
```

```{r Plot Generation}
Model_Comparison_Plot <- ggplot(Results, aes(x = forcats::fct_relevel(Model, mean_order), y = AUROC, color = Model)) +
  geom_boxplot(outlier.colour = NA, fatten = NULL) + 
  geom_jitter() +
  labs(y = "Balanced AUC", x = " ") +
  theme(axis.title = element_text(face = 'bold', size = '16'),
        axis.text.x = element_text(size = 10, face = 'bold'),
        plot.title = element_text(face = 'bold', hjust = 0.5, size = 14),
        axis.title.y = element_text(hjust = 0.45),
        legend.position = "bottom",
        axis.line = element_line(color = 'black', linewidth = 0.5),
        panel.background = element_rect(fill = 'white')) +
  scale_y_continuous(limits= c(0, 1.35), breaks=seq(0,1, 0.1)) +
  annotate(geom="text", x=1, y=0.05, label=round(Means[4,2], 3),
            color="black", size=4) +
  annotate(geom="text", x=2, y=0.05, label=round(Means[3,2], 3),
            color="black", size=4) +
  annotate(geom="text", x=3, y=0.05, label=round(Means[2,2], 3),
            color="black", size=4) +
  annotate(geom="text", x=4, y=0.05, label=round(Means[1,2], 3),
            color="black", size=4) +
  theme(legend.position = "none")

Model_Comparison_Plot

ggsave("../figures/RF_irae_boxplots.png", height = 4, width = 6, dpi = 400)
```



