---
title: "aucpr_and_cfm_template"
author: "Noah Lepola"
date: "2025-02-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(randomForest)
library(ROCR)
library(caTools)
library(openxlsx)
library(respondersig) 
library(PRROC)

```

Loading file
```{r}
source("../scripts/mitox_functions.R")
# irAE_aucprs <- readRDS("../data/rf_mitox_irAE_aucpr.RData")
# Response_aucprs <- readRDS("../data/rf_mitox_Response_aucpr.RData")
# load("../../manuscript/data/ra-long.rds")
load("../../manuscript/data/clinical.rds")
load("../../manuscript/data/blood.rds")
load("../../manuscript/data/microbiome_metadata.rds")
# load("../../manuscript/data/phylum-labels.rds")
# load("../../manuscript/data/ANCOM-BC2_response_baseline.Rdata")
# load("../../manuscript/data/ANCOM-BC2_irae_baseline.RData")
# load("../../manuscript/data/core-score-min3.rds")

```





```{r}
seed_list <- c(12345:12369)
```


Making objects for q value models
```{r}

#Object to limit microbiome sample to one ones taken within 10 days of treatment
baseline <- mic.meta %>%
  group_by(`Patient Id`) %>%
  arrange(Days) %>%
  slice_head(n = 1) %>%
  ungroup() %>%
  filter(abs(Days) <= 10) %>%
  subset(`Patient Id` %in% blood$`Patient Id`)

```



Splitting the data into training and testing for mitox models
```{r}
set.seed(42301)

#splitting data into train and test
split <- sample.split(demographics$Response, SplitRatio = 0.5)

train  <- subset(demographics, split == TRUE) %>%
  subset(`Patient Id` %in% blood$`Patient Id`) %>%
  subset(`Patient Id` %in% baseline$`Patient Id`)

test   <- subset(demographics, split == FALSE) %>%
  subset(`Patient Id` %in% blood$`Patient Id`) %>%
  subset(`Patient Id` %in% baseline$`Patient Id`)

train.outcomes <- demographics %>%
  select(`Patient Id`, Response) %>%
  subset(`Patient Id` %in% train$`Patient Id`) %>%
  subset(`Patient Id` %in% blood$`Patient Id`) %>%
  subset(`Patient Id` %in% baseline$`Patient Id`)

train.outcomes <- arrange(train.outcomes, desc(`Patient Id`))


test.outcomes <- demographics %>%
  select(`Patient Id`, Response) %>%
  subset(`Patient Id` %in% test$`Patient Id`) %>%
  subset(`Patient Id` %in% blood$`Patient Id`) %>%
  subset(`Patient Id` %in% baseline$`Patient Id`)

test.outcomes <- arrange(test.outcomes, desc(`Patient Id`))
```


Data for clinical model
```{r}
#Making data objects for blood only model

clinical <- demographics %>%
  subset(`Patient Id` %in% blood$`Patient Id`) %>%
  subset(`Patient Id` %in% baseline$`Patient Id`) %>%
  select(`Patient Id`, Age, `BMI.(kg/m2)`) 


train.seq <- clinical %>%
  subset(`Patient Id` %in% train$`Patient Id`)

test.seq <- clinical %>%
  subset(`Patient Id` %in% test$`Patient Id`)
```



microbiome only model
```{r}
load("../data/responseAUCPRavgs.RData")
source("../scripts/mitox_functions.R")

# Response
rf_AgeBMI_Response_list <- kTest(seed_list, "Non-Responder", "Responder", "Response", 500)

aucprs <- grabVals(aucprs, rf_AgeBMI_Response_list, seed_list)

Response_clinical <- mean(aucprs$AUCPR)

Response_clinical <- as.data.frame(Response_clinical) %>%
  rename(AUCPR = Response_clinical) %>%
  add_column("name" = "Response_clinical", .before = "AUCPR")

responseAUCPRavgs <- responseAUCPRavgs  %>%
  add_row(Response_clinical)
# responseAUCPRavgs <- responseAUCPRavgs[-c(1),]
```


```{r}
save(rf_AgeBMI_Response_list, file = "../data/rf_AgeBMI_Response_list.RData")
save(responseAUCPRavgs, file = "../data/responseAUCPRavgs.RData")
load("../data/responseAUCPRavgs.RData")

```

