---
title: "aucpr_and_cfm_template"
author: "Noah Lepola"
date: "2025-02-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(randomForest)
library(ROCR)
library(caTools)
library(openxlsx)
library(respondersig) 
library(PRROC)

```

Loading file
```{r}
source("../scripts/mitox_functions.R")
# irAE_aucprs <- readRDS("../data/rf_mitox_irAE_aucpr.RData")
# Response_aucprs <- readRDS("../data/rf_mitox_Response_aucpr.RData")
load("../../manuscript/data/ra-long.rds")
load("../../manuscript/data/clinical.rds")
load("../../manuscript/data/blood.rds")
load("../../manuscript/data/microbiome_metadata.rds")
load("../../manuscript/data/phylum-labels.rds")
load("../../manuscript/data/ANCOM-BC2_response_baseline.Rdata")
load("../../manuscript/data/ANCOM-BC2_irae_baseline.RData")
load("../../manuscript/data/core-score-min3.rds")

# responseAUCPRavgs <- data.frame(name = NA, AUCPR = NA)
```


Making objects for q value models
```{r}

#Object to limit microbiome sample to one ones taken within 10 days of treatment
baseline <- mic.meta %>%
  group_by(`Patient Id`) %>%
  arrange(Days) %>%
  slice_head(n = 1) %>%
  ungroup() %>%
  filter(abs(Days) <= 10) %>%
  subset(`Patient Id` %in% blood$`Patient Id`)


#limiting blood samples to ones also with microbiome sample and creating object
base.gene <- blood %>%
  subset(`Patient Id` %in% baseline$`Patient Id`) %>%
  select(`Patient Id`:YWHAZ)



phyl_labels <- phyl_labels %>%
  mutate(taxon = substr(microbe, 4, nchar(microbe)))

#creating object for use in biome model
base.micro <- ra.l %>%
  pivot_wider(names_from = microbe, values_from = RelAbun) %>%
  subset(sample %in% baseline$sample)

#note it is dropping bacteria and archaea becaise it isn't in phyl_labels
#making object for irAE where q < 0.005
Response_q <- res.recist %>%
  left_join(phyl_labels) %>%
  select(microbe, q_ResponseResponder)  %>%
  filter(q_ResponseResponder < 0.005) %>%
  replace_na(list( microbe = "k__Archaea"))



Response_list <- Response_q$microbe %>%
  append("Patient Id", after = 0)

Response_list[[1]] <- "Patient Id"


```


Splitting the data into training and testing for mitox models
```{r}
set.seed(42301)

#splitting data into train and test
split <- sample.split(demographics$Response, SplitRatio = 0.5)

train  <- subset(demographics, split == TRUE) %>%
  subset(`Patient Id` %in% blood$`Patient Id`) %>%
  subset(`Patient Id` %in% baseline$`Patient Id`)

test   <- subset(demographics, split == FALSE) %>%
  subset(`Patient Id` %in% blood$`Patient Id`) %>%
  subset(`Patient Id` %in% baseline$`Patient Id`)

train.outcomes <- demographics %>%
  select(`Patient Id`, irAE, Response) %>%
  subset(`Patient Id` %in% train$`Patient Id`) %>%
  subset(`Patient Id` %in% blood$`Patient Id`) %>%
  subset(`Patient Id` %in% baseline$`Patient Id`)

train.outcomes <- arrange(train.outcomes, desc(`Patient Id`))


test.outcomes <- demographics %>%
  select(`Patient Id`, irAE, Response) %>%
  subset(`Patient Id` %in% test$`Patient Id`) %>%
  subset(`Patient Id` %in% blood$`Patient Id`) %>%
  subset(`Patient Id` %in% baseline$`Patient Id`)

test.outcomes <- arrange(test.outcomes, desc(`Patient Id`))
```




Making q value and struct 0 objects for Response
```{r}
microlim <- baseline %>%
  select(sample, `Patient Id`) %>%
  full_join(base.micro, baseline, by = "sample") %>%
  select(-sample)


microlim <- microlim %>%
  select((Response_list))

treatment <- demographics %>%
  select(`Patient Id`, Treatment)

treatment$Treatment <- as.factor(treatment$Treatment)


blood.and.biome <-  full_join(microlim, base.gene, by = "Patient Id") %>%
  subset(`Patient Id` %in% baseline$`Patient Id`)

blood_biome_treatment <-  full_join(treatment, blood.and.biome, by = "Patient Id") %>%
  subset(`Patient Id` %in% baseline$`Patient Id`)

train.seq <- filter(blood_biome_treatment,
                    (`Patient Id` %in% train.outcomes$`Patient Id`)) 


train.seq <- arrange(train.seq, desc(`Patient Id`))



test.seq <- filter(blood_biome_treatment,
                    (`Patient Id` %in% test.outcomes$`Patient Id`))
test.seq <- arrange(test.seq, desc(`Patient Id`))
```





microbiome only model
```{r}
load("../data/responseAUCPRavgs.RData")
seed_list <- c(12345:12369)


# Response
rf_q005wBloodwTreatment <- kTest(seed_list, "Non-Responder", "Responder", "Response", 500)

aucprs <- grabVals(aucprs, rf_q005wBloodwTreatment, seed_list)

response_q005wBloodwTreatment <- mean(aucprs$AUCPR)

response_q005wBloodwTreatment <- as.data.frame(response_q005wBloodwTreatment) %>%
  rename(AUCPR = response_q005wBloodwTreatment) %>%
  add_column("name" = "response_q005wBloodwTreatment", .before = "AUCPR")

responseAUCPRavgs <- responseAUCPRavgs  %>%
  add_row(response_q005wBloodwTreatment)
# responseAUCPRavgs <- responseAUCPRavgs[-c(1),]
```


```{r}
save(responseAUCPRavgs, file = "../data/responseAUCPRavgs.RData")
load("../data/responseAUCPRavgs.RData")

```

