---
title: "top_irae_mics"
author: "Caroline Wheeler"
date: "2/28/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
```

```{r}
load("../manuscript/data/deseq_recist.rds")
load("../manuscript/data/deseq_recist_baseline.rds")
load("../manuscript/data/microbiome.rds")
load("../manuscript/data/taxonomy.rds")
load("../manuscript/data/blood.rds")
load("../manuscript/data/microbiome_metadata.rds")
```

```{r}
top.mics <- resPlot_recist %>%
  arrange(padj) %>%
  slice_head(n = 10) 
```

create data frame to append to blood data for RF
```{r}
exoRAtowide <- function(data, taxlev){
  tmp <- data
  tmp$Taxa <- tmp[[taxlev]]
  tmp.wide<- tmp %>%
    filter(!is.na(Taxa)) %>%
    group_by(sample, Taxa) %>%
    summarise(ra.tot = sum(RelAbun, na.rm = T)) %>%
    pivot_wider(names_from = "Taxa", values_from = "ra.tot", values_fill = 0)

  return(tmp.wide)
}

fam <- exoRAtowide(tax.tab, "family")
gen <- exoRAtowide(tax.tab, "genus")
spec <- exoRAtowide(tax.tab, "species")

tmp <- merge(fam, gen)
tax.wide <- merge(tmp, spec) %>%
  select(sample, rownames(top.mics)) 
# %>%
# # remove two genus level that only have 1 species, so relAbun is the same
#   select(-g__Jerseyvirus, -g__Rb49virus)
```

```{r}
baseline <- mic.meta %>%
  group_by(`Patient Id`) %>%
  arrange(Days) %>%
  slice_head(n = 1)

tax.wide <- tax.wide %>%
  filter(sample %in% baseline$sample)
```

save top mics 
```{r}
write.csv(tax.wide, "../data/top_irae_mics.csv", row.names = F)
```

## Effect Size Plot 

plot effect size
```{r}
top.mics <- top.mics %>%
  rownames_to_column("Microbe") %>%
  filter(Microbe %in% colnames(tax.wide)) %>%
  mutate(Microbe = substr(Microbe, 4, nchar(Microbe))) 

top.mics %>%
  ggplot(aes(x = log2FoldChange, y = reorder(Microbe, log2FoldChange))) +
  geom_bar(stat = "identity", fill =  "#D55E00") + 
  theme_minimal() +
  ylab("Microbe") +
  xlab("Effect Size") +
  ggtitle("No <-- irAE --> Yes") +
  theme(plot.title = element_text(hjust = 0.04))

ggsave(file = "../figures/irAEmics_effectSize.png", dev = "png", width = 6, height = 4, dpi = 600)
```

## AHR correlation 

prep

```{r}
ahr <- blood %>%
  select(`Patient Id`, AHR)

tax.wide <- tax.wide %>%
  left_join(mic.meta) %>%
  left_join(ahr) %>%
  select(-sample, -`Patient Id`, -sample_id, -Days)
```

```{r}
res <- as.data.frame(cor(tax.wide, method = "spearman", use="complete.obs")) %>%
  select(AHR) 

res <- res %>%
  filter(rownames(res) != "AHR") %>%
  rownames_to_column("Microbe") %>%
  mutate(Microbe = substr(Microbe, 4, nchar(Microbe)),
         Gene = "AHR") %>%
  rename("Correlation" = AHR) %>%
  left_join(top.mics)
```

plot
```{r}
res %>%
  ggplot(aes(x = Gene, y=reorder(Microbe, log2FoldChange), fill=Correlation)) +
  geom_tile() +
  theme_minimal() +
  coord_equal() +
  ylab("Microbe")

ggsave("../figures/AHR_heatmap.png", width = 5, height = 5)
```

